camera_directory:
  ros__parameters:
    serial_overrides:
      roots:
        arm: platform-3530000.xhci-usb-0:3
camera_streamer:
  ros__parameters:
    cameras:
      arm_end_periscope:
        meta:
          ros_topic: "/arm/periscope"
