# Request
# Where to move the motor to
string pump
float32 time_to_run
---
# Result
# Whether the motor was able to move to the requested position
bool success
---
# Feedback
# How many steps are left to reach the requested position
float32 time_running
float32 time_to_run