camera_streamer:
  ros__parameters:
    defaults:
      width: 640
      framerate: 10
      profiles:
        snail:
          width: 320
          framerate: 7.5

    cameras:
      # Mast
      mast_backward:
        meta:
          uiProps:
            name: Mast - Backwards
      mast_arm_stow:
        meta:
          uiProps:
            name: Mast - Arm Stow
      mast_down:
        meta:
          uiProps:
            name: Mast - Down
      mast_forward:
        meta:
          uiProps:
            name: Mast - Forwards

      # Science
      science_microscope:
        meta:
          uiProps:
            name: Science - Microscope
            rotation: 180
      science_gantry:
        meta:
          uiProps:
            name: Science - Gantry
            rotation: 180
      science_spectrometer_side:
        meta:
          uiProps:
            name: Science - Spectrometer (Side)
            rotation: 180
      science_backward:
        meta:
          uiProps:
            name: Science - Butt
            rotation: 180
      science_rock_flipper:
        meta:
          uiProps:
            name: Science - Rock flipper

      # Arm
      arm_gimbal:
        meta:
          uiProps:
            name: Arm - Gimbal
      arm_end_screw:
        meta:
          uiProps:
            name: Arm - Screw
            mirrorX: true
      arm_end_top:
        meta:
          uiProps:
            name: Arm - Top
      arm_end_finger:
        meta:
          uiProps:
            name: Arm - Finger
      arm_end_forward:
        meta:
          uiProps:
            name: Arm - Forwards
