camera_directory:
  ros__parameters:
    serial_overrides:
      paths:
        mast:
          '1:1.0': mast_backward
          '2:1.0': mast_arm_stow
          '3:1.0': mast_down
          '4:1.0': mast_forward
        arm:
          '1:1.0': arm_gimbal
          '2.1:1.0': arm_end_screw
          '2.2:1.0': arm_end_top
          '2.3:1.0': arm_end_finger
          '2.4:1.0': arm_end_forward
