teleop_drive:
  ros__parameters:
    # The maximum rate at which updates should occur, and hence the max rate at which commands are sent.
    # Leaving this unset makes the max update rate unlimited.
    update_rate: 100.0

    # The minimum rate at which updates occur.
    # Leaving this unset will allow for indefinite lapses between updates.
    min_update_rate: 2.0

    input_sources:
      names:
        - game_controller_source

      # Declare types for the sources
      game_controller_source:
        type: "teleop_modular_joy/JoyInputSource"

    control_modes:
      names:
        # First in the list gets activated at startup
        - pivot_mode
        - strafe_mode
        - tank_mode

      # Declare types for the modes
      pivot_mode:
        type: "teleop_modular_twist/TwistControlMode"
        controllers:
          - pivot_drive_controller

      strafe_mode:
        type: "teleop_modular_twist/TwistControlMode"
        controllers:
          - strafe_drive_controller

      tank_mode:
        type: "teleop_modular_twist/TwistControlMode"
        controllers:
          - diff_drive_controller

    commands:
      names:
        - enter_pivot_mode
        - enter_strafe_mode
        - enter_tank_mode
        - lock
        - unlock
        - log_locked
        - log_unlocked
        - set_initial_speed
        - speed_up_coarse
        - speed_down_coarse
        - speed_up_fine
        - speed_down_fine

      enter_pivot_mode:
        on: "pivot_mode/down"
        type: "switch_control_mode"
        to: "pivot_mode"
      enter_strafe_mode:
        on: "strafe_mode/down"
        type: "switch_control_mode"
        to: "strafe_mode"
      enter_tank_mode:
        on: "tank_mode/down"
        type: "switch_control_mode"
        to: "tank_mode"
      lock:
        on_any: ["lock/down", "start"]
        type: "set_button"
        name: "locked"
        value: true
      unlock:
        on: "unlock/up"
        type: "set_button"
        name: "locked"
        value: false
      log_locked:
        on: "locked/down"
        type: "log"
        message: "Locked"
      log_unlocked:
        on: "locked/up"
        type: "log"
        message: "Unlocked"

      set_initial_speed:
        on: "start"
        type: "set_axis"
        name: "speed"
        value: 0.0
      speed_up_coarse:
        on_any: ["speed_up_coarse/down", "start"]
        type: "increment_axis"
        name: "speed"
        by: 0.1
        until: 1.0
      speed_up_fine:
        on: "speed_up_fine/down"
        type: "increment_axis"
        name: "speed"
        by: 0.01
        until: 1.0
      speed_down_coarse:
        on: "speed_down_coarse/down"
        type: "increment_axis"
        name: "speed"
        by: -0.1
        until: 0.0
      speed_down_fine:
        on: "speed_down_fine/down"
        type: "increment_axis"
        name: "speed"
        by: -0.01
        until: 0.0


game_controller_source:
  ros__parameters:
    topic: "/joy"
    # These are the default mappings for a game_controller_node.
    # https://docs.ros.org/en/ros2_packages/rolling/api/joy/index.html
    # If you use joy_node, you'll need to figure out what the mapping is yourself.
    # So, run joy, `ros2 topic echo /joy`, and mess around with your controller to figure out what it is for you.
    button_definitions: [
      "A",
      "B",
      "X",
      "Y",
      "BACK",
      "GUIDE",
      "START",
      "LEFTSTICK",
      "RIGHTSTICK",
      "LEFTSHOULDER",
      "RIGHTSHOULDER",
      "DPAD_UP",
      "DPAD_DOWN",
      "DPAD_LEFT",
      "DPAD_RIGHT",
      "MISC1",
      "PADDLE1",
      "PADDLE2",
      "PADDLE3",
      "PADDLE4",
      "TOUCHPAD"
    ]
    axis_definitions: [
      "LEFTX",
      "LEFTY",
      "RIGHTX",
      "RIGHTY",
      "TRIGGERLEFT",
      "TRIGGERRIGHT"
    ]

    remap:
      axes:
        linear:
          x:
            from: "LEFTY"
        angular:
          z:
            from: "RIGHTX"
        speed:
          from: "TRIGGERRIGHT"
          invert: true

      buttons:
        pivot_mode:
          from: "RIGHTSHOULDER"
        strafe_mode:
          from: "LEFTSHOULDER"
        tank_mode:
          from: "Y"
        lock:
          from: "BACK"
        unlock:
          from: "START"
        speed_up_coarse:
          from: "DPAD_UP"
        speed_down_coarse:
          from: "DPAD_DOWN"
        speed_up_fine:
          from: "DPAD_RIGHT"
        speed_down_fine:
          from: "DPAD_LEFT"


pivot_mode:
  ros__parameters:
    stamped_topic: "/cmd_vel"
    # stamped_topic: "/some_stamped_topic"
    qos: 10

    use_speed_input: true

    scale:
      linear:
        x: 1.0
      angular:
        z: 3.14

strafe_mode:
  ros__parameters:
    stamped_topic: "/cmd_vel"
    # stamped_topic: "/some_stamped_topic"
    qos: 10

    use_speed_input: true

    scale:
      linear:
        x: 1.0
      angular:
        z: 3.14

tank_mode:
  ros__parameters:
    stamped_topic: "/cmd_vel"
    # stamped_topic: "/some_stamped_topic"
    qos: 10

    use_speed_input: true

    scale:
      linear:
        x: 1.0
      angular:
        z: 3.14
