# thrustmaster joystick input source for 2025 E&C payload

teleop_ec:
  ros__parameters:

    input_sources:
      names: [
        "thrustmaster_left",
        "thrustmaster_right"
      ]

      thrustmaster_left:
        type: "teleop_modular_joy/JoyInputSource"
      thrustmaster_right:
        type: "teleop_modular_joy/JoyInputSource"



thrustmaster_left:
  ros__parameters:
    topic: "/ec/joy/left"

    button_definitions: [
      "btn_thumb_u_state",        # Up / Trigger (behind the thumbstick)
      "btn_thumb_d_state",        # Down
      "btn_thumb_l_state",        # Buttons located near the thumb stick (Left)
      "btn_thumb_r_state",        # Right
      "btn_bottom_l1_state",      # Buttons located at the bottom left
      "btn_bottom_l2_state",      # Numbered Left to Right, First then Second row
      "btn_bottom_l3_state",      # Ordered top left to right, bottom right to left
      "btn_bottom_l6_state",
      "btn_bottom_l5_state",
      "btn_bottom_l4_state",
      "btn_bottom_r3_state",      # Buttons located at the bottom right
      "btn_bottom_r2_state",      # Numbered Left to Right, First then Second row
      "btn_bottom_r1_state",      # Ordered top right to left, bottom left to right
      "btn_bottom_r4_state",
      "btn_bottom_r5_state",
      "btn_bottom_r6_state"
    ]

    axis_definitions: [
      "ax_stick_x",               # Left/right
      "ax_stick_y",               # Forward/backwards
      "ax_stick_twist",           # Twist
      "ax_slider",
      "ax_thumb_x",               # Thumb Axis Data (left/right)
      "ax_thumb_y"                # Each Thumb axis can be -1, 0 or 1 (up/down)
    ]

    remap:
      axes:
        arm_actuation:
          from: "ax_stick_y"

        forklift_speed:
          from: "ax_slider"
          range:
            in: [ -1.0, 1.0 ]
            out: [ 0.0, 1.0 ]
            clamp: true

        forklift_actuation:
          from: "ax_thumb_x"

      buttons:
        lock:
          from: "btn_bottom_l2_state"

        unlock:
          from: "btn_bottom_l5_state"



thrustmaster_right:
  ros__parameters:
    topic: "/ec/joy/right"

    button_definitions: [
      "btn_thumb_u_state",        # Up / Trigger (behind the thumbstick)
      "btn_thumb_d_state",        # Down
      "btn_thumb_l_state",        # Buttons located near the thumb stick (Left)
      "btn_thumb_r_state",        # Right
      "btn_bottom_l1_state",      # Buttons located at the bottom left
      "btn_bottom_l2_state",      # Numbered Left to Right, First then Second row
      "btn_bottom_l3_state",      # Ordered top left to right, bottom right to left
      "btn_bottom_l6_state",
      "btn_bottom_l5_state",
      "btn_bottom_l4_state",
      "btn_bottom_r3_state",      # Buttons located at the bottom right
      "btn_bottom_r2_state",      # Numbered Left to Right, First then Second row
      "btn_bottom_r1_state",      # Ordered top right to left, bottom left to right
      "btn_bottom_r4_state",
      "btn_bottom_r5_state",
      "btn_bottom_r6_state"
    ]

    axis_definitions: [
      "ax_stick_x",               # Left/right
      "ax_stick_y",               # Forward/backwards
      "ax_stick_twist",           # Twist
      "ax_slider",
      "ax_thumb_x",               # Thumb Axis Data (left/right)
      "ax_thumb_y"                # Each Thumb axis can be -1, 0 or 1 (up/down)
    ]

    remap:
      axes:
        scraper_speed:
          from: "ax_slider"
          range:
            in: [-1.0, 1.0]
            out: [0.0, 1.0]
            clamp: true

        scoop_actuation:
          from: "ax_stick_y"

        claw_actuation:
          from: "ax_thumb_x"