teleop_science:
  ros__parameters:
    # The maximum rate at which updates should occur, and hence the max rate at which commands are sent.
    # Leaving this unset makes the max update rate unlimited.
    # update_rate: 50.0

    # The minimum rate at which updates occur.
    # Leaving this unset will allow for indefinite lapses between updates.
    #min_update_rate: 2.0

    input_sources:
      names:
        - "game_controller_source"

      # Declare types for the sources
      game_controller_source:
        type: "teleop_modular_joy/JoyInputSource"

    control_modes:
      names:
        # First in the list gets activated at startup
        - "legacy_input_mode"

      # Declare types for the modes
      legacy_input_mode:
        display_name: "Legacy Input Publisher"
        type: "legacy_input_mode/LegacyInputMode"
        active: true

game_controller_source:
  ros__parameters:
    topic: "/joy"
    # These are the default mappings for a game_controller_node.
    # https://docs.ros.org/en/ros2_packages/rolling/api/joy/index.html
    # If you use joy_node, you'll need to figure out what the mapping is yourself.
    # So, run joy, `ros2 topic echo /joy`, and mess around with your controller to figure out what it is for you.
    button_definitions: [
      "A",
      "B",
      "X",
      "Y",
      "BACK",
      "GUIDE",
      "START",
      "LEFTSTICK",
      "RIGHTSTICK",
      "LEFTSHOULDER",
      "RIGHTSHOULDER",
      "DPAD_UP",
      "DPAD_DOWN",
      "DPAD_LEFT",
      "DPAD_RIGHT",
      "MISC1",
      "PADDLE1",
      "PADDLE2",
      "PADDLE3",
      "PADDLE4",
      "TOUCHPAD"
    ]
    axis_definitions: [
      "LEFTX",
      "LEFTY",
      "RIGHTX",
      "RIGHTY",
      "TRIGGERLEFT",
      "TRIGGERRIGHT"
    ]

    remap:
      axes:
        ax_stick_x:
          from: "RIGHTY"
        ax_stick_y:
          from: "RIGHTX"

      buttons:
        # lock
        btn_bottom_l2_state:
          from: "BACK"
        # unlock
        btn_bottom_l5_state:
          from: "START"

legacy_input_mode:
  ros__parameters:
    topic: "/inputs/input_joystick_l"
