camera_directory:
  ros__parameters:
    blacklist:
      # These serials will not be broadcasted by the directory server
      
      # The RealSense cameras expose many video device nodes, all with the same serial number and USB device path. 
      # This is incompatible with the current design of the camera_directory node. But could be fixed in the future...
      - Intel_R__RealSense_TM__Depth_Camera_455_Intel_R__RealSense_TM__Depth_Camera_455_210523060485
      - Intel_R__RealSense_TM__Depth_Camera_455_Intel_R__RealSense_TM__Depth_Camera_455 # Jetson TX2 does not see the serial number??

    serial_overrides:
      # cameras at the specified root.path combo will have their serials overridden as specified by the platform and task passed to the directory node
      platform_roots:
        # the root for each platform which generally will change depending on which usb slot of the device the usb hub is plugged into
        # the root can be specified by passing the "platform" parameter to the directory node
        intel_laptop:
          "pci-0000:00:14.0-usb-0:1": mast
          "pci-0000:00:14.0-usb-0:2": payload
        orin:
          "platform-3610000.usb-usb-0:3": mast
          "platform-3610000.usb-usb-0:2": payload
        orin_dev_board:
          "platform-3610000.usb-usb-0:2.1": mast
          "platform-3610000.usb-usb-0:2.1.4": payload 
          # Expected USB slots:
          # -------------------------------------
          # ---- | Mast hub     |      | --------
          # HDMI | Payload hub  |      | ETHERNET
          # -------------------------------------

      default_paths:
        # by default these paths on the usb hub will be remapped to the following serials.
        # these default serials can be overridden in tasks
        # the path corresponds to the slot on a usb hub
        mast:
          '1:1.0': mast_arm_stow
          '2:1.0': mast_belly
          '3:1.0': mast_backward
          '4:1.0': mast_forward
        payload:
          '1:1.0': payload_1
          '2:1.0': payload_2
          '3:1.0': payload_3
          '4:1.0': payload_4
          '4.1:1.0': payload_4_1
          '4.2:1.0': payload_4_2
          '4.3:1.0': payload_4_3
          '4.4:1.0': payload_4_4


      task_paths:
        # the set of overrides can be selected by setting the "task" parameter
        # if a non-default path is needed, it can be specified in its named root followed by the path.
        # Take a look at example for the possible override methods
        science-urc:
          payload_1: science_gimbal_cam
          payload_2: science_microscope
          payload_3: science_spectroscope
          payload:
            '4.1:1.0': science_cuvettes
        delivery:
          payload_1: arm_end_side
          payload_2: arm_end_finger
          payload_3: arm_end_periscope
          payload_4_2: arm_end_top
          payload_4_4: arm_wrist

        auto:
          mast_arm_stow: auto_left
          mast_down: auto_right
          mast_forward: auto_forward
          mast_backward: auto_behind

        example:
          payload_2: science_kiln
          mast_arm_stow: science_microscope
          'payload.4.1:1.2': science_cuvettes
          mast:
            '1:1.0': bellycam
            '2:1.0': jared_left_eye

    serial_remaps:
      # serial_remaps can be used to override a camera serial into another serial in the directory message and is typically used in testing
      # a serial remap occurs after an override, so you can essentially rename an override! 
      # These are global overrides and will occur irrespective of platform and task.
      046d_C270_HD_WEBCAM_2A3D8660: anthony-cam
