camera_streamer:
  ros__parameters:
    autostart: true
    serial_pipelines:

      # Development cameras
      anthony-cam:
        pipeline_type: h264passthrough
        width: 1920
        height: 1080
        framerate: 30

      # Mast
      mast_backward:
        meta : Mast - Backwards
      mast_arm_stow:
        meta: Mast - Arm Stow
      mast_down:
        meta: Mast - Down
      mast_forward:
        meta: Mast - Forwards

      # Science
      science_microscope:
        pipeline_type: vpXsoftware
        mime: video/x-raw
        width: 640
        framerate: 25
        meta: Science - Microscope
      science_gantry:
        meta: Science - Gantry
      science_spectrometer_top:
        meta: Science - Spectrometer (Top)
      science_spectrometer_side:
        meta: Science - Spectrometer (Side)
      science_backward:
        meta: Science - Butt
      science_shotglass:
        meta: Science - Shotglass
      science_rock_flipper:
        meta: Science - Rock flipper
      #science_spectroscope:
      #  autostart: false

      # Arm
      arm_gimbal:
        meta: Arm - Gimbal
      arm_end_forward:
        meta: Arm - Forward
      arm_end_top:
        meta: Arm - Top
      arm_end_finger:
        meta: Arm - Finger
      arm_end_side:
        meta: Arm - Side

    profiles:
      openaicam_openaicam_2505121128:
        🛞:
          pipeline_type: vpXsoftware
          mime: image/jpeg
          width: 1280
          height: 720
          framerate: 30
          downscale: 2
          crop43: true
          cpu_usage: 0
          bitrate: 576
          video_caps: video/x-vp8
        🔬:
          pipeline_type: h264software
          mime: video/x-raw
          width: 1920
          height: 1080
          framerate: 5
          cpu_usage: 16
          bitrate: 4096
          speed-preset: slow
          threads: 6
          video_caps: video/x-h264
        📻:
          pipeline_type: vpXsoftware
          mime: image/jpeg
          width: 1280
          height: 720
          framerate: 30
          downscale: 6
          crop43: true
          cpu_usage: 8
          bitrate: 256
          video_caps: video/x-vp9
        🆘:
          pipeline_type: vpXsoftware
          width: 1280
          height: 720
          framerate: 30
          downscale: 12
          crop43: true
          cpu_usage: 16
          bitrate: 64
          video_caps: video/x-vp9

      webcamvendor_SK_series1_20220325JWGD2093:
        🛞:
          pipeline_type: h264passthrough
          width: 640
          height: 480
          framerate: 30
        🔬:
          pipeline_type: h264passthrough
          width: 1920
          height: 1080
          framerate: 30
        📻:
          pipeline_type: h264passthrough
          width: 320
          height: 240
          framerate: 30
        🆘:
          pipeline_type: vpXsoftware
          width: 320
          height: 240
          framerate: 30
          downscale: 5
          crop43: true
          cpu_usage: 16
          bitrate: 64
          video_caps: video/x-vp9

      HZ_USB_Camera_20220301104:
        🛞:
          pipeline_type: vpXsoftware
          mime: image/jpeg
          width: 1280
          height: 720
          framerate: 30
          downscale: 2
          crop43: true
          cpu_usage: 0
          bitrate: 576
          video_caps: video/x-vp8
        🔬:
          pipeline_type: h264software
          mime: video/x-raw
          width: 2592
          height: 1944
          framerate: 1
          cpu_usage: 16
          bitrate: 4096
          speed-preset: slow
          threads: 6
          video_caps: video/x-h264
        📻:
          pipeline_type: vpXsoftware
          mime: image/jpeg
          width: 640
          height: 480
          framerate: 30
          downscale: 4
          crop43: true
          cpu_usage: 8
          bitrate: 256
          video_caps: video/x-vp9
        🆘:
          pipeline_type: vpXsoftware
          width: 640
          height: 480
          framerate: 30
          downscale: 10
          crop43: true
          cpu_usage: 16
          bitrate: 64
          video_caps: video/x-vp9

      Microsoft_Microsoft®_LifeCam_HD-3000:
        🛞:
          pipeline_type: vpXsoftware
          mime: image/jpeg
          width: 640
          height: 360
          framerate: 30
          crop43: true
          cpu_usage: 0
          bitrate: 576
          video_caps: video/x-vp8
        🔬:
          pipeline_type: h264software
          mime: video/x-raw
          width: 1280
          height: 800
          framerate: 10
          downrate: 2
          bitrate: 4096
          speed-preset: slow
          threads: 6
          video_caps: video/x-h264
        📻:
          pipeline_type: vpXsoftware
          mime: image/jpeg
          width: 160
          height: 120
          framerate: 30
          crop43: true
          cpu_usage: 8
          bitrate: 256
          video_caps: video/x-vp9
        🆘:
          pipeline_type: vpXsoftware
          width: 320
          height: 240
          framerate: 30
          downscale: 5
          crop43: true
          cpu_usage: 16
          bitrate: 64
          video_caps: video/x-vp9


    defaults:
      # Waveshare
      openaicam_openaicam_2505121128:
        pipeline_type: vpXsoftware
        width: 1280
        height: 720
        crop43: true
        framerate: 30
        noise_reduction: 128

      webcamvendor_SK_series1_20220325JWGD2093:
        pipeline_type: h264passthrough
        width: 1920
        height: 1080
        framerate: 30
        noise_reduction: 1024
        payload_quirk: true

      HZ_USB_Camera_20220301104:
        pipeline_type: vpXsoftware
        width: 1024
        height: 768
        framerate: 30
        noise_reduction: 256
        brightness: 256

      # Legacy
      Microsoft_Microsoft®_LifeCam_HD-3000:
        pipeline_type: vpXsoftware
        width: 800
        height: 600
        framerate: 30
        noise_reduction: 128

      # Name violates yaml rules
      # Ricoh_Company__Ltd._RICOH_THETA_Z1_34122798:
      #  pipeline_type: h264passthrough
      #  width: 3840
      #  height: 1920
      #  framerate: 30000
      #  framerate_denominator: 1001
      #  noise_reduction: 256

