camera_streamer:
  ros__parameters:  
    serial_pipelines:
      # Development cameras
      anthony-cam:
        pipeline_type: h264passthrough
        width: 1920
        height: 1080
        framerate: 30

      # Mast
      mast_backward:
        meta : Mast - Backwards
      mast_arm_stow:
        meta: Mast - Arm Stow
      mast_belly:
        meta: Mast - Down
      mast_forward:
        meta: Mast - Forwards

      # Science
      science_microscope:
        meta: Science - Microscope
      science_gantry:
        meta: Science - Gantry
      science_spectrometer_top:
        meta: Science - Spectrometer (Top)
      science_spectrometer_side:
        meta: Science - Spectrometer (Side)
      science_backward:
        meta: Science - Butt
      science_shotglass:
        meta: Science - Shotglass
      science_rock_flipper:
        meta: Science - Rock flipper
      #science_spectroscope:
      #  autostart: false

      # Arm
      arm_gimbal:
        meta: Arm - Gimbal
      arm_end_periscope:
        meta: Arm - Periscope
      arm_end_top:
        meta: Arm - Top
      arm_end_finger:
        meta: Arm - Finger
      arm_end_side:
        meta: Arm - Side

    profiles:
      unknown:
        default:
          pipeline_type: vp8software
          mime: image/jpeg
          width: 1920
          height: 1080
          downscale: 3
          framerate: 30
          cpu_usage: 0
          noise: 6
          bitrate: 512
        super:
          pipeline_type: vp9software
          mime: image/jpeg
          width: 1920
          height: 1080
          framerate: 30
          downrate: 3
          cpu_usage: 2
          jpegdec_method: float
          bitrate: 2048
          threads: 6
          gop: 3
        snail: 
          pipeline_type: vp9software
          width: 640
          height: 480
          downscale: 2
          framerate: 30
          downrate: 2
          cpu_usage: 7
          noise: 6
          bitrate: 128
        emergency:
          pipeline_type: vp9software
          width: 640
          height: 480
          downscale: 5
          framerate: 30
          downrate: 4
          cpu_usage: 10
          noise: 6
          bitrate: 32
          greyscale: true

      openaicam_openaicam_2505121128:
        default:
          pipeline_type: vp8software
          mime: image/jpeg
          width: 1920
          height: 1080
          downscale: 3
          framerate: 30
          cpu_usage: 0
          noise: 6
          bitrate: 512
        super:
          pipeline_type: vp9software
          mime: image/jpeg
          width: 1920
          height: 1080
          framerate: 30
          downrate: 3
          cpu_usage: 2
          jpegdec_method: float
          bitrate: 2048
          threads: 6
          gop: 3
        snail:
          pipeline_type: vp9software
          width: 1920
          height: 1080
          downscale: 4
          framerate: 30
          downrate: 2
          cpu_usage: 7
          noise: 6
          bitrate: 128
        emergency:
          pipeline_type: vp9software 
          width: 1920
          height: 1080
          downscale: 12
          framerate: 30
          downrate: 4
          cpu_usage: 10
          noise: 6
          bitrate: 32
          greyscale: true

      webcamvendor_SK_series1_20220325JWGD2093:
        default:
          pipeline_type: h264passthrough
          width: 640
          height: 480
          framerate: 30
        super:
          pipeline_type: h264passthrough
          width: 1280
          height: 960
          framerate: 30
        snail:
          pipeline_type: h264passthrough
          width: 320
          height: 240
          downrate: 2
          framerate: 30
        emergency:
          pipeline_type: vp9software
          width: 1280
          height: 960
          downscale: 10
          framerate: 30
          downrate: 4
          cpu_usage: 10
          noise: 6
          bitrate: 32
          greyscale: true

      HZ_USB_Camera_20220301104:
        default:
          pipeline_type: vp8software
          mime: image/jpeg
          width: 1024
          height: 768
          downscale: 2
          framerate: 30
          cpu_usage: 0
          noise: 6
          bitrate: 512
        super:
          pipeline_type: vp9software
          mime: image/jpeg
          width: 1024
          height: 768
          framerate: 30
          downrate: 3
          cpu_usage: 2
          jpegdec_method: float
          bitrate: 2048 
          threads: 6
          gop: 3
        snail: 
          pipeline_type: vp9software
          width: 640
          height: 480
          downscale: 2
          framerate: 30
          downrate: 2
          cpu_usage: 7
          noise: 6
          bitrate: 128
        emergency:
          pipeline_type: vp9software
          width: 640
          height: 480
          downscale: 5
          framerate: 30
          downrate: 4
          cpu_usage: 10
          noise: 6
          bitrate: 32
          greyscale: true

      Microsoft_Microsoft®_LifeCam_HD-3000:
        default:
          pipeline_type: vp8software
          width: 1280
          height: 720
          downscale: 2
          framerate: 30
          cpu_usage: 0
          noise: 6
          bitrate: 512
        super:
          pipeline_type: vp9software
          mime: image/jpeg
          width: 800
          height: 600
          framerate: 30
          downrate: 3
          cpu_usage: 4
          jpegdec_method: float
          bitrate: 2048
          threads: 6
          gop: 3
        snail:
          pipeline_type: vp9software
          width: 1280
          height: 720
          downscale: 3
          framerate: 30
          downrate: 2
          cpu_usage: 7
          noise: 6
          bitrate: 128
        emergency:
          pipeline_type: vp9software
          width: 1280
          height: 720
          downscale: 8
          framerate: 30
          downrate: 4
          cpu_usage: 10
          noise: 6
          bitrate: 32
          greyscale: true

    presets:
      # auto:
      delivery:
        drive:
          mast_forward: default
          mast_backward: default
          mast_arm_stow: default
          mast_belly: default
          arm_end_periscope: snail
          arm_end_top: snail
          arm_end_finger: snail
          arm_end_side: snail
        payload:
          mast_forward: snail
          mast_backward: snail
          mast_arm_stow: snail
          mast_belly: snail
          arm_end_periscope: default
          arm_end_top: default
          arm_end_finger: default
          arm_end_side: default

      # science:

    defaults:
      # Waveshare
      openaicam_openaicam_2505121128:
        pipeline_type: vp8software
        width: 1280
        height: 720
        framerate: 30
        verify_resolution: false

      webcamvendor_SK_series1_20220325JWGD2093:
        pipeline_type: h264passthrough
        width: 1920
        height: 1080
        framerate: 30
        verify_resolution: false
        payload_quirk: true

      HZ_USB_Camera_20220301104:
        pipeline_type: vp9software
        width: 1024
        height: 768
        framerate: 30
        verify_resolution: false
        brightness: 255

      # Legacy
      Microsoft_Microsoft®_LifeCam_HD-3000:
        pipeline_type: vp8software
        width: 800
        height: 600
        framerate: 30
        verify_resolution: false

      GenesysLogic_Technology_Co.__Ltd._USB2.0_UVC_PC_Camera:
        pipeline_type: vp9software
        mime: video/x-raw
        width: 640
        height: 480
        framerate: 25
        cpu_usage: 7
        bitrate: 1024
        threads: 6
        gop: 3
        verify_resolution: false

      # Name violates yaml rules
      # Ricoh_Company__Ltd._RICOH_THETA_Z1_34122798:
      #  pipeline_type: h264passthrough
      #  width: 3840
      #  height: 1920
      #  framerate: 30000
      #  framerate_denominator: 1001
      #  noise_reduction: 256

