camera_streamer:
  ros__parameters:  
    serial_pipelines:
      # Development cameras
      anthony-cam:
        pipeline_type: h264passthrough
        width: 1920
        height: 1080
        framerate: 30

      # Mast
      mast_backward:
        meta : Mast - Backwards
      mast_arm_stow:
        meta: Mast - Arm Stow
      mast_belly:
        meta: Mast - Down
      mast_forward:
        meta: Mast - Forwards

      # Science
      science_microscope:
        meta: Science - Microscope
        pipeline_type: vp9software
        mime: video/x-raw
        width: 640
        height: 480
        framerate: 25
        cpu_usage: 5
        bitrate: 1024
        gop: 3
      science_gantry:
        meta: Science - Gantry
      science_spectrometer_top:
        meta: Science - Spectrometer (Top)
      science_spectrometer_side:
        meta: Science - Spectrometer (Side)
      science_backward:
        meta: Science - Butt
      science_shotglass:
        meta: Science - Shotglass
      science_rock_flipper:
        meta: Science - Rock flipper
      #science_spectroscope:
      #  autostart: false

      # Arm
      arm_wrist:
        meta: Arm - Wrist 
      arm_end_periscope:
        meta: Arm - Periscope
      arm_end_top:
        meta: Arm - Top
      arm_end_finger:
        meta: Arm - Finger
      arm_end_side:
        meta: Arm - Side

    profiles:
      unknown:
        default:
          pipeline_type: vp8software
          width: 1920
          height: 1080
          downscale: 3
          framerate: 30
          cpu_usage: 0
          bitrate: 512
        super:
          pipeline_type: vp9software
          width: 1280
          height: 720
          framerate: 30
          downrate: 3
          cpu_usage: 5
          jpegdec_method: float
          bitrate: 1024
          threads: 6
          gop: 3
          noise: 0
        still:
          pipeline_type: vp9software
          width: 1920
          height: 1080
          downscale: 2
          framerate: 30
          downrate: 3
          cpu_usage: 5
          jpegdec_method: float
          bitrate: 256
          gop: 5
          noise: 1
        snail:
          pipeline_type: vp8software
          width: 640
          height: 480
          downscale: 2
          framerate: 30
          downrate: 2
          cpu_usage: 0
          bitrate: 128
          denoise: true
          noise: 6
        emergency:
          pipeline_type: vp9software
          width: 640
          height: 480
          downscale: 5
          framerate: 30
          downrate: 4
          cpu_usage: 8
          bitrate: 32
          greyscale: true
          denoise: true
          noise: 6

      openaicam_openaicam_2505121128:
        default:
          pipeline_type: vp8software
          width: 1920
          height: 1080
          downscale: 3
          framerate: 30
          cpu_usage: 0
          bitrate: 512
        super:
          pipeline_type: vp9software
          width: 1280
          height: 720
          framerate: 30
          downrate: 3
          cpu_usage: 5
          jpegdec_method: float
          bitrate: 1024
          threads: 6
          gop: 3
          noise: 0
        still:
          pipeline_type: vp9software
          width: 1920
          height: 1080
          downscale: 2
          framerate: 30
          downrate: 3
          cpu_usage: 5
          jpegdec_method: float
          bitrate: 256
          gop: 5
          noise: 1
        snail:
          pipeline_type: vp8software
          width: 1920
          height: 1080
          downscale: 4
          framerate: 30
          downrate: 2
          cpu_usage: 0
          bitrate: 128
          denoise: true
          noise: 6
        emergency:
          pipeline_type: vp9software
          width: 1920
          height: 1080
          downscale: 12
          framerate: 30
          downrate: 4
          cpu_usage: 8
          bitrate: 32
          greyscale: true
          denoise: true
          noise: 6

      webcamvendor_SK_series1_20220325JWGD2093:
        default:
          pipeline_type: h264passthrough
          width: 640
          height: 480
          framerate: 30
        super:
          pipeline_type: h264passthrough
          width: 1280
          height: 960
          framerate: 30
        still:
          pipeline_type: vp9software
          mime: image/jpeg
          width: 1280
          height: 960
          downscale: 2
          framerate: 30
          downrate: 3
          cpu_usage: 5
          jpegdec_method: float
          bitrate: 256
          gop: 5
        snail:
          pipeline_type: h264passthrough
          width: 320
          height: 240
          framerate: 30
        emergency:
          pipeline_type: vp9software
          width: 1280
          height: 960
          downscale: 10
          framerate: 30
          downrate: 8
          cpu_usage: 10
          bitrate: 32
          greyscale: true

      HZ_USB_Camera_20220301104:
        default:
          pipeline_type: vp8software
          mime: image/jpeg
          width: 1024
          height: 768
          downscale: 2
          framerate: 30
          cpu_usage: 0
          bitrate: 512
        super:
          pipeline_type: vp9software
          mime: image/jpeg
          width: 1024
          height: 768
          framerate: 30
          downrate: 3
          cpu_usage: 5
          jpegdec_method: float
          bitrate: 1024
          threads: 6
          gop: 3
          noise: 0
        still:
          pipeline_type: vp9software
          mime: image/jpeg
          width:  1024
          height: 768
          downscale: 2
          framerate: 30
          downrate: 3
          cpu_usage: 5
          jpegdec_method: float
          bitrate: 256
          gop: 5
          noise: 1
        snail: 
          pipeline_type: vp8software
          width: 640
          height: 480
          downscale: 2
          framerate: 30
          downrate: 2
          cpu_usage: 0
          bitrate: 128
          denoise: true
        emergency:
          pipeline_type: vp9software
          width: 640
          height: 480
          downscale: 5
          framerate: 30
          downrate: 4
          cpu_usage: 8
          bitrate: 32
          greyscale: true

      Microsoft_Microsoft®_LifeCam_HD-3000:
        default:
          pipeline_type: vp8software
          width: 1280
          height: 720
          downscale: 2
          framerate: 30
          cpu_usage: 0
          bitrate: 512
        super:
          pipeline_type: vp9software
          mime: image/jpeg
          width: 800
          height: 600
          framerate: 30
          downrate: 3
          cpu_usage: 5
          jpegdec_method: float
          bitrate: 2048
          threads: 6
          gop: 3
          noise: 0
        still:
          pipeline_type: vp9software
          mime: image/jpeg
          width: 1280
          height: 720
          downscale: 2
          framerate: 10
          cpu_usage: 5
          jpegdec_method: float
          bitrate: 256
          gop: 5
          noise: 1
        snail:
          pipeline_type: vp8software
          width: 1280
          height: 720
          downscale: 3
          framerate: 30
          downrate: 2
          cpu_usage: 0
          bitrate: 128
          denoise: true
        emergency:
          pipeline_type: vp9software
          width: 1280
          height: 720
          downscale: 8
          framerate: 30
          downrate: 4
          cpu_usage: 8
          bitrate: 32
          greyscale: true
          denoise: true

    presets:
      auto:
        drive:
          auto_left: default
          auto_right: default
          auto_forward: default 
          auto_behind: snail
        payload:
          auto_left: still
          auto_right: still
          auto_forward: still
          auto_behind: snail

      delivery:
        drive:
          mast_forward: default
          mast_backward: default
          mast_arm_stow: default
          mast_belly: default
          arm_end_periscope: snail
          arm_end_top: snail
          arm_end_finger: snail
          arm_end_side: snail
          arm_wrist: snail
        payload:
          mast_forward: snail
          mast_backward: snail
          mast_arm_stow: snail
          mast_belly: snail
          arm_end_periscope: default
          arm_end_top: default
          arm_end_finger: default
          arm_end_side: default
          arm_wrist: default

      science-urc:
        drive:
          mast_forward: snail
          mast_backward: default
          mast_arm_stow: default
          mast_belly: default

          science_cache_left: snail
          science_cache_right: snail
          science_microscope: snail

          science_gimbal_cam: default
          science_boom: snail
          science_cuvettes: snail

          science_litmus: default
          science_spectroscope: snail
        payload:
          mast_forward: still
          mast_backward: snail
          mast_arm_stow: snail
          mast_belly: snail

          science_cache_left: snail
          science_cache_right: snail
          science_microscope: default

          science_gimbal_cam: default
          science_boom: default
          science_cuvettes: default

          science_litmus: still
          science_spectroscope: still

    defaults:
      # Waveshare
      openaicam_openaicam_2505121128:
        pipeline_type: vp8software
        width: 1280
        height: 720
        framerate: 30

      webcamvendor_SK_series1_20220325JWGD2093:
        pipeline_type: h264passthrough
        width: 1920
        height: 1080
        framerate: 30
        payload_quirk: true
        denoise: true
        denoise_sigma: 12.0
        denoise_threshold: 0.15
        denoise_radius: 4
        undistort: true
        undistort_k1: -0.11
        undistort_k2: 0.01

      HZ_USB_Camera_20220301104:
        pipeline_type: vp9software
        width: 1024
        height: 768
        framerate: 30
        brightness: 255
        undistort: true
        undistort_k1: -0.08
        undistort_k2: 0.007

      # Legacy
      Microsoft_Microsoft®_LifeCam_HD-3000:
        pipeline_type: vp8software
        width: 800
        height: 600
        framerate: 30

      # Name violates yaml rules
      # Ricoh_Company__Ltd._RICOH_THETA_Z1_34122798:
      #  pipeline_type: h264passthrough
      #  width: 3840
      #  height: 1920
      #  framerate: 30000
      #  framerate_denominator: 1001

