# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# 

version: 2
updates:
  - package-ecosystem: "npm" # See documentation for possible values (yarn = npm)
    directory: "/src/ros/nova-gui/nova-gui" # Location of package manifests
    schedule:
      interval: "daily" # Packages will be very out of date so will do it regularly for a bit then make this longer.
    open-pull-requests-limit: 10 # Will likely reduce later as well.
