ros_streamer:
  ros__parameters:
    # Note the node doesn't currently work with depth cameras (needs some conversion in gstreamer pipeline)
    cameras: oak-rgb bootie-rgb
    oak-rgb:
      topic: /oak/rgb/gui
      serial: oak-rgb
    bootie-rgb:
      topic: /bootie/rgb/gui
      serial: bootie-rgb
    