/**
 * Auto-generated ROS message TypeScript definitions.
 *
 * This file is normally generated by ros-typescript-generator during the Nix
 * build and symlinked into place. It is gitignored by design.
 *
 * This stub was created so that the project can type-check outside the full
 * Nix build environment. The types below were inferred from usage across the
 * codebase. Run the Nix build to regenerate from the real .msg/.srv/.action
 * definitions if precision is needed.
 */

// ─── Common sub-types ───────────────────────────────────────────────

export interface IRosStdMsgsHeader {
  stamp: { sec: number; nanosec: number };
  frame_id: string;
}

// ─── std_msgs ───────────────────────────────────────────────────────

export interface IRosStdMsgsString {
  data: string;
}

export interface IRosStdMsgsBool {
  data: boolean;
}

export interface IRosStdMsgsFloat64 {
  data: number;
}

// ─── geometry_msgs ──────────────────────────────────────────────────

export interface IRosGeometryMsgsPose {
  orientation: { x: number; y: number; z: number; w: number };
  position: { x: number; y: number; z: number };
}

// ─── sensor_msgs ────────────────────────────────────────────────────

export interface IRosSensorMsgsJoy {
  header: IRosStdMsgsHeader;
  axes: number[];
  buttons: number[];
}

export interface IRosSensorMsgsJointState {
  name: string[];
  position: number[];
  velocity: number[];
  effort: number[];
}

export interface IRosSensorMsgsRange {
  header: IRosStdMsgsHeader;
  min_range: number;
  max_range: number;
  range: number;
}

export interface IRosSensorMsgsCompressedImage {
  data: number[];
  format: string;
}

export interface IRosSensorMsgsBatteryState {
  header: IRosStdMsgsHeader;
  voltage: number;
  temperature: number;
  current: number;
  charge: number;
  capacity: number;
  design_capacity: number;
  percentage: number;
  power_supply_status: number;
  power_supply_health: number;
  power_supply_technology: number;
  present: boolean;
  cell_voltage: number[];
  cell_temperature: number[];
  location: string;
  serial_number: string;
}

// ─── std_srvs ───────────────────────────────────────────────────────

export interface IRosStdSrvsTriggerResponse {
  success: boolean;
  message: string;
}

export interface IRosStdSrvsSetBoolResponse {
  success: boolean;
  message: string;
}

// ─── cmd_interfaces (arm motor feedback) ────────────────────────────

export interface IRosCmdInterfacesCmdFeedback {
  header: IRosStdMsgsHeader;
  bus: number;
  id: number;
  omega: number;
  vel: number;
  duty_cycle: number;
  current: number;
  interval: number;
}

export interface IRosCmdInterfacesCmDsFeedback {
  header: IRosStdMsgsHeader;
  wheels: IRosCmdInterfacesCmdFeedback[];
  wheel_pivots: IRosCmdInterfacesCmdFeedback[];
  arm_motors: IRosCmdInterfacesCmdFeedback[];
  science_motors: IRosCmdInterfacesCmdFeedback[];
}

// ─── drive_interfaces ───────────────────────────────────────────────

export interface IRosDriveInterfacesDriveInfo {
  multiplier: number;
  locked: boolean;
  locked_reason: number;
  autonomous_mode: boolean;
  connected: boolean;
  drive_mode: number;
  handbrake: boolean;
  override_autolock: boolean;
}

// ─── blcmd_interfaces ───────────────────────────────────────────────

export interface IRosBlcmdInterfacesBlcmdStatus {
  id: number;
  gate_fault: boolean;
  stall_fault: boolean;
  resolver_fault: boolean;
  overspeed_fault: boolean;
  overacceleration_fault: boolean;
  encoder_fault: boolean;
}

export interface IRosBlcmdInterfacesBlcmdStatusArray {
  blcmds: IRosBlcmdInterfacesBlcmdStatus[];
}

export interface IRosBlcmdInterfacesSingleTelemetry {
  bus: string;
  id: number;
  rotor_velocity: number;
  q_current: number;
  rotor_interval: number;
  d_current: number;
  resolver_position: number;
  resolver_velocity: number;
  power: number;
  voltage: number;
  temperature: number;
}

export interface IRosBlcmdInterfacesTelemetry {
  wheels: IRosBlcmdInterfacesSingleTelemetry[];
  pivots: IRosBlcmdInterfacesSingleTelemetry[];
}

export interface IRosBlcmdInterfacesBlcmdResetRequest {
  type: number;
  id: number;
}

export interface IRosBlcmdInterfacesBlcmdResetResponse {
  success: boolean;
}

export enum IRosBlcmdInterfacesBlcmdResetRequestConst {
  BLCMD = 1,
  RESOLVER = 2,
}

// ─── nova_interfaces ────────────────────────────────────────────────

export enum IRosNovaInterfacesStatusConst {
  IDLE = 0,
  TRAVERSING = 1,
  SEARCHING = 2,
  ARRIVED_SUCCESSFULLY = 3,
  ARRIVED_UNSUCCESSFULLY = 4,
}

export interface IRosNovaInterfacesStatus {
  status: number;
}

export interface IRosNovaInterfacesGpsData {
  header: IRosStdMsgsHeader;
  latitude: number;
  longitude: number;
  altitude: number;
  heading: number;
}

export interface IRosNovaInterfacesCartographerCommandRequest {
  goals: Array<{ latitude: number; longitude: number }>;
  goal_type: number;
  search_radius: number;
}

export interface IRosNovaInterfacesCartographerCommandResponse {
  success: boolean;
}

export interface IRosNovaInterfacesActiveNodeStatus {
  name: string;
  active: boolean;
  locked: boolean;
}

export interface IRosNovaInterfacesRadioStatus {
  stamp: { sec: number; nanosec: number };
  recv: number;
  sent: number;
  ping: number;
  signal: number;
}

export interface IRosNovaInterfacesLockedStatus {
  locked: boolean;
}

export interface IRosNovaInterfacesRgbInputRequest {
  r: number;
  g: number;
  b: number;
  flash: boolean;
}

export interface IRosNovaInterfacesRgbInputResponse {
  success: boolean;
}

export interface IRosNovaInterfacesDetection2D {
  class_name: string;
  score: number;
  pose: IRosGeometryMsgsPose;
  image_width: number;
  image_height: number;
}

export interface IRosNovaInterfacesDetection2DArray {
  header: IRosStdMsgsHeader;
  detections: IRosNovaInterfacesDetection2D[];
}

// ─── camera_msgs ────────────────────────────────────────────────────

export interface IRosCameraMsgsCamera {
  serial: string;
  node: string;
  original_serial: string;
  profile: string;
  pipeline_type: string;
}

export interface IRosCameraMsgsCameras {
  cameras: IRosCameraMsgsCamera[];
}

export interface IRosCameraMsgsCameraOperationRequest {
  serials: string[];
}

export interface IRosCameraMsgsCameraOperationResponse {
  success: boolean;
}

export interface IRosCameraMsgsCameraProfileSelectionRequest {
  serials: string[];
  profile: string;
}

export interface IRosCameraMsgsCameraProfileSelectionResponse {
  success: boolean;
}

export interface IRosCameraMsgsGetIpListResponse {
  ips: string[];
}

// ─── arm_interfaces ─────────────────────────────────────────────────

export interface IRosArmInterfacesKeyboardPoints {
  points: number[];
  width: number;
  height: number;
}

export interface IRosArmInterfacesSequencerFeedback {
  sequence: string[];
  partial_sequence: string[];
  current_key: string;
}

export interface IRosArmInterfacesTypeSequenceRequest {
  sequence: string[];
}

export interface IRosArmInterfacesTypeSequenceResponse {
  success: boolean;
  message: string;
}

export interface IRosArmInterfacesStringTriggerResponse {
  success: boolean;
  message: string;
}

// ─── rcl_interfaces ─────────────────────────────────────────────────

export interface IRosRclInterfacesSetParametersRequest {
  parameters: Array<{
    name: string;
    value: {
      type: number;
      bool_value?: boolean;
      [key: string]: unknown;
    };
  }>;
}

export interface IRosRclInterfacesSetParametersResponse {
  results: Array<{
    successful: boolean;
    reason: string;
  }>;
}

// ─── science_interfaces (topics) ────────────────────────────────────

export interface IRosScienceInterfacesThermalData {
  stamp: { sec: number; nanosec: number };
  temp: number[];
  state: boolean;
}

export interface IRosScienceInterfacesNirProbeData {
  data: number[];
  status: boolean;
  reading_taken: boolean;
}

export interface IRosScienceInterfacesEffortStatus {
  state: boolean;
}

export interface IRosScienceInterfacesMicroscopeServoInfo {
  angle: number;
}

export interface IRosScienceInterfacesHydraprobeData {
  conductivity: number;
  moisture: number;
  temperature: number;
  dielectric: number;
}

export interface IRosScienceInterfacesBmeSensor {
  temperature: number;
  humidity: number;
  pressure: number;
  altitude: number;
}

export interface IRosScienceInterfacesRamanSpectrum {
  isvalid: boolean;
  spectrum: number[];
}

export interface IRosScienceInterfacesRamanState {
  green_laser_on: boolean;
  red_laser_on: boolean;
  filter_selection: number;
  stepper_value: number;
  mirror_servo: number;
}

export interface IRosScienceInterfacesUvVisSpecData {
  luminance: number[];
}

export interface IRosScienceInterfacesPumpStatus {
  running: boolean;
  pump: string;
  time_elapsed: number;
  time_target: number;
}

export interface IRosScienceInterfacesCarouselFeedback {
  position: number;
  zeroing: boolean;
  hall_effect_triggered: boolean;
  is_moving: boolean;
}

export interface IRosScienceInterfacesPotentiostatData {
  header: IRosStdMsgsHeader;
  channel: number;
  voltage: number;
  current: number;
  is_receiving: boolean;
}

export interface IRosScienceInterfacesNamedBools {
  names: string[];
  values: boolean[];
}

// ─── science_interfaces (services) ──────────────────────────────────

export interface IRosScienceInterfacesThermalCommandRequest {
  state: boolean;
  target: number;
}

export interface IRosScienceInterfacesThermalCommandResponse {
  success: boolean;
}

export interface IRosScienceInterfacesEffortCommandRequest {
  state: boolean;
  level: number;
}

export interface IRosScienceInterfacesEffortCommandResponse {
  success: boolean;
}

export interface IRosScienceInterfacesRamanSpecRequest {
  port: string;
  shperiod: number;
  icgperiod: number;
  average: number;
  singlecollectionmode: boolean;
  continuousendsignal: boolean;
}

export interface IRosScienceInterfacesRamanSpecResponse {
  continuousendedsignal: boolean;
}

export interface IRosScienceInterfacesRamanMechRequest {
  green_laser_on: boolean;
  red_laser_on: boolean;
  filter_selection: number;
  stepper_value: number;
  mirror_servo: number;
}

export interface IRosScienceInterfacesRamanMechResponse {
  success: boolean;
}

export interface IRosScienceInterfacesMoveScimbalCamRequest {
  angles: [number, number];
}

export interface IRosScienceInterfacesMoveScimbalCamResponse {
  success: boolean;
}

export interface IRosScienceInterfacesTakeNirProbeReadingRequest {
  led: number;
}

export interface IRosScienceInterfacesTakeNirProbeReadingResponse {
  success: boolean;
}

export interface IRosScienceInterfacesSetPositionRequest {
  position: number;
}

export interface IRosScienceInterfacesSetPositionResponse {
  success: boolean;
}

export interface IRosScienceInterfacesPowerCycleRequest {
  sleep_duration: number;
}

export interface IRosScienceInterfacesPowerCycleResponse {
  success: boolean;
  message: string;
}

export interface IRosScienceInterfacesSetNamedBoolRequest {
  name: string;
  value: boolean;
}

export interface IRosScienceInterfacesSetNamedBoolResponse {
  success: boolean;
}

export interface IRosScienceInterfacesSetNamedPositionsRequest {
  names: string[];
  positions: number[];
}

export interface IRosScienceInterfacesSetNamedPositionsResponse {
  success: boolean;
}

export interface IRosScienceInterfacesIncrementZeroRequest {
  reset_zero: boolean;
  increment_zero: number;
}

export interface IRosScienceInterfacesIncrementZeroResponse {
  success: boolean;
}

export interface IRosScienceInterfacesRunPumpRequest {
  pump: string;
  duration: number;
}

export interface IRosScienceInterfacesRunPumpResponse {
  success: boolean;
  message: string;
}

export interface IRosScienceInterfacesTriggerOptionRequest {
  option: number;
}

export interface IRosScienceInterfacesTriggerOptionResponse {
  success: boolean;
  message: string;
}

// ─── science_interfaces (actions) ───────────────────────────────────

export interface IRosScienceInterfacesStepperActionGoal {
  goal: string;
  action: number;
}

export interface IRosScienceInterfacesStepperActionResult {
  success: boolean;
}

export interface IRosScienceInterfacesStepperActionFeedback {
  current_position: number;
  goal_position: number;
}
