teleop_arm_joy_node:
  ros__parameters:
    joint_definitions: [
      "arm_j1",
      "arm_j2",
      "arm_j3",
      "arm_j4",
      "arm_j5",
      "arm_j6"
    ]
    axis_definitions: [
      "arm_j1",
      "arm_j2",
      "arm_j3",
      "arm_j4",
      "arm_j5",
      "arm_j6",
      "speed",
      "offset",
      "twist_x",
      "twist_y",
      "twist_z",
      "twist_yaw",
      "twist_pitch",
      "twist_roll"
    ]

    twist:
      linear_max: 0.25
      angular_max: 0.364467013889
    joints:
      arm_j1:
        max_speed: 0.364467013889
      arm_j2:
        max_speed: 0.364467013889
      arm_j3:
        max_speed: 0.364467013889
      arm_j4:
        max_speed: 0.364467013889
      arm_j5:
        max_speed: 0.364467013889
      arm_j6:
        max_speed: 0.364467013889
    device_names: ["Left", "Right"]
    devices:
      Left:
        topic: "/joy_L"
      Right:
        topic: "/joy_R"
    axes:
      arm_j1:
        device: "Left"
        id: 2
      arm_j2:
        device: "Left"
        id: 0
      arm_j3:
        device: "Left"
        id: 1
        invert: true
      arm_j4:
        device: "Right"
        id: 1
        invert: true
      arm_j5:
        device: "Right"
        id: 0
      arm_j6:
        device: "Right"
        id: 2

      speed:
        device: "Right"
        id: 3
      offset:
        device: "Left"
        id: 3

      twist_x:
        device: "Right"
        id: 1
      twist_y:
        device: "Right"
        id: 0
      twist_z:
        device: "Right"
        id: 2
        invert: true

      twist_roll:
        device: "Left"
        id: 0
      twist_pitch:
        device: "Left"
        id: 1
        invert: true
      twist_yaw:
        device: "Left"
        id: 2
      
      

    buttons:
      twist_mode:
        device: "Right"
        id: 0
      limit_on:
        device: "Left"
        id: 4
      limit_off:
        device: "Left"
        id: 9
      lock:
        device: "Left"
        id: 5
      unlock:
        device: "Left"
        id: 8

# trigger:
#   id: 0
# top down:
#   id: 1
# top left:
#   id: 2
# top right:
#   id: 0
