teleop_arm_joy_node:
  ros__parameters:
    twist:
      linear_max: 0.25
      angular_max: 1.57079632679
    joints:
      J1:
        max_speed: 0.785398163395
      J2:
        max_speed: 0.785398163395
      J3:
        max_speed: 0.785398163395
      J4:
        max_speed: 0.785398163395
      J5:
        max_speed: 0.785398163395
      J6:
        max_speed: 0.785398163395
    device_names: ["Gamepad"]
    devices:
      Gamepad:
        topic: "/joy"
    axes:
      J1:
        device: "Gamepad"
        button_id_negative: 13
        button_id_positive: 14
      J2:
        device: "Gamepad"
        button_id_negative: 11
        button_id_positive: 12
      J3:
        device: "Gamepad"
        button_id_negative: 0
        button_id_positive: 3
        invert: true

      J4:
        device: "Gamepad"
        id: 1
      J5:
        device: "Gamepad"
        id: 3
        invert: true
      J6:
        device: "Gamepad"
        button_id_negative: 1
        button_id_positive: 2

      speed:
        device: "Gamepad"
        id: 5
#      offset:
#        device: "Gamepad"
#        id: 4


      twist_x:
        device: "Gamepad"
        button_id_negative: 11
        button_id_positive: 12
        invert: true
      twist_y:
        device: "Gamepad"
        button_id_negative: 13
        button_id_positive: 14
        invert: true
      twist_z:
        device: "Gamepad"
        button_id_negative: 0
        button_id_positive: 3

      twist_yaw:
        device: "Gamepad"
        id: 2
      twist_pitch:
        device: "Gamepad"
      twist_roll:
        device: "Gamepad"

    buttons:
      twist_mode:
        device: "Gamepad"
        id: 9
#      limit_on:
#        device: "Gamepad"
#        id: 4
#      limit_off:
#        device: "Gamepad"
#        id: 9
      lock:
        device: "Gamepad"
        id: 4
      unlock:
        device: "Gamepad"
        id: 6

# trigger:
#   id: 0
# top down:
#   id: 1
# top left:
#   id: 2
# top right:
#   id: 0
