teleop_arm_joy_node:
  ros__parameters:
#    update_rate: 40.0
#    min_update_rate: 0.5

    # Declare modes and sources to spawn
    control_modes: [
      "joint_space_control",
      "twist_ik_control"
    ]
    input_sources: [
      "joy_input_source"
    ]

    joint_space_control:
      type: "teleop_arm_joy/JointSpaceControlMode"

    twist_ik_control:
      type: "teleop_arm_joy/TwistIKControlMode"

    fake_type_mode:
      type: "teleop_arm_joy/Fake"

    joy_input_source:
      type: "teleop_arm_joy/JoyInputSource"

    joints:
      J1:
        max_speed: 0.785398163395
      J2:
        max_speed: 0.785398163395
      J3:
        max_speed: 0.785398163395
      J4:
        max_speed: 0.785398163395
      J5:
        max_speed: 0.785398163395
      J6:
        max_speed: 0.785398163395

joint_control_mode:
  ros__parameters:
    bruh:
      "bruh"

joy_input_source:
  ros__parameters:
    joint_definitions: [
      "arm_j1",
      "arm_j2",
      "arm_j3",
      "arm_j4",
      "arm_j5",
      "arm_j6"
    ]
    axis_definitions: [
      "arm_j1",
      "arm_j2",
      "arm_j3",
      "arm_j4",
      "arm_j5",
      "arm_j6",
      "speed",
      "offset",
      "twist_x",
      "twist_y",
      "twist_z",
      "twist_yaw",
      "twist_pitch",
      "twist_roll"
    ]
    button_definitions: [
      "twist_mode",
      "limit_on",
      "limit_off",
      "lock",
      "unlock"
    ]

    twist:
      linear_max: 0.25
      angular_max: 0.785398163395
    joints:
      arm_j1:
        max_speed: 0.364467013889
      arm_j2:
        max_speed: 0.364467013889
      arm_j3:
        max_speed: 0.364467013889
      arm_j4:
        max_speed: 0.364467013889
      arm_j5:
        max_speed: 0.364467013889
      arm_j6:
        max_speed: 0.364467013889
    device_names: ["gamepad"]
    devices:
      gamepad:
        topic: "/joy"
    axes:
      arm_j1:
        device: "gamepad"
        id: 6
      arm_j2:
        device: "gamepad"
        id: 7
        invert: true
      arm_j3:
        device: "gamepad"
        button_id_negative: 0
        button_id_positive: 3
        invert: true

      arm_j4:
        device: "gamepad"
        id: 4
      arm_j5:
        device: "gamepad"
        id: 3
#        button_id_negative: 2
#        button_id_positive: 1
      arm_j6:
        device: "gamepad"
        button_id_negative: 1
        button_id_positive: 2

      speed:
        device: "gamepad"
        id: 5
        invert: true
#      offset:
#        device: "gamepad"
#        id: 4


      twist_x:
        device: "gamepad"
        id: 6
      twist_y:
        device: "gamepad"
        id: 7
      twist_z:
        device: "gamepad"
        button_id_negative: 0
        button_id_positive: 3

      twist_yaw:
        device: "gamepad"
        id: 3
      twist_pitch:
        device: "gamepad"
        id: 4
        invert: true
      twist_roll:
        device: "gamepad"
        button_id_negative: 2
        button_id_positive: 1

    buttons:
      twist_mode:
        device: "gamepad"
        id: 4
      limit_on:
        device: "gamepad"
        id: 4
      limit_off:
        device: "gamepad"
        id: 9
      lock:
        device: "gamepad"
        id: 7
      unlock:
        device: "gamepad"
        id: 6


# trigger:
#   id: 0
# top down:
#   id: 1
# top left:
#   id: 2
# top right:
#   id: 0
