teleop_arm_joy_node:
  ros__parameters:
    update_rate: 100.0
    min_update_rate: 0.5

    # Set this true to display all the inputs. Very useful when trying to make a config!
    log_inputs: false

    control_modes:
      # Declare the names of your control modes here
      names: [
        "joint_space_control",
        "task_space_control"
      ]
      joint_space_control:
        type: "teleop_arm_joy/JointSpaceControlMode"
        controllers: [
          "nova_arm_velocity_controller"
        ]
      task_space_control:
        type: "teleop_arm_joy/TwistControlMode"
        controllers: [
          "nova_arm_position_controller"
          "nova_twistmapper"
        ]

    input_sources:
      # Declare the names of your input sources here
      names: [
        "joy_input_source"
      ]
      joy_input_source:
        type: "teleop_arm_joy/JoyInputSource"

    commands:
      # Declare the names of your commands here
      names: [
        "enter_twist_ik_control",
        "enter_joint_space_control",
        "log_locked",
        "log_unlocked",
      ]

      # Configure your commands here.
      enter_twist_ik_control:
        on: "twist_mode/down"
        type: "switch_control_mode"
        to: "twist_ik_control"
      enter_joint_space_control:
        on: "twist_mode/up"
        type: "switch_control_mode"
        to: "joint_space_control"

      # Locking and unlocking
      log_locked:
        on: "locked/down"
        type: "log"
        message: "Locked"
      log_unlocked:
        on: "locked/up"
        type: "log"
        message: "Unlocked"

joint_space_control:
  ros__parameters:
    joint_definitions: [
      "arm_j1",
      "arm_j2",
      "arm_j3",
      "arm_j4",
      "arm_j5",
      "arm_j6"
    ]

    joints:
      arm_j1:
        input_name: "J1"
        max_speed: 0.364467013889
      arm_j2:
        input_name: "J2"
        max_speed: 0.364467013889
      arm_j3:
        input_name: "J3"
        max_speed: 0.364467013889
      arm_j4:
        input_name: "J4"
        max_speed: 0.364467013889
      arm_j5:
        input_name: "J5"
        max_speed: 0.364467013889
      arm_j6:
        input_name: "J6"
        max_speed: 0.364467013889

joy_input_source:
  ros__parameters:
    joint_definitions: [
      "J1",
      "J2",
      "J3",
      "J4",
      "J5",
      "J6"
    ]
    axis_definitions: [
      "J1",
      "J2",
      "J3",
      "J4",
      "J5",
      "J6",
      "speed",
      "offset",
      "twist_x",
      "twist_y",
      "twist_z",
      "twist_yaw",
      "twist_pitch",
      "twist_roll"
    ]
    button_definitions: [
      "twist_mode",
      "limit_on",
      "limit_off",
      "lock",
      "unlock"
    ]

    twist:
      linear_max: 0.25
      angular_max: 0.785398163395
    joints:
      J1:
        max_speed: 0.364467013889
      J2:
        max_speed: 0.364467013889
      J3:
        max_speed: 0.364467013889
      J4:
        max_speed: 0.364467013889
      J5:
        max_speed: 0.364467013889
      J6:
        max_speed: 0.364467013889
    device_names: ["gamepad"]
    devices:
      gamepad:
        topic: "/joy"
    axes:
      J1:
        device: "gamepad"
        id: 6
      J2:
        device: "gamepad"
        id: 7
        invert: true
      J3:
        device: "gamepad"
        button_id_negative: 0
        button_id_positive: 3
        invert: true

      J4:
        device: "gamepad"
        id: 4
      J5:
        device: "gamepad"
        id: 3
#        button_id_negative: 2
#        button_id_positive: 1
      J6:
        device: "gamepad"
        button_id_negative: 1
        button_id_positive: 2

      speed:
        device: "gamepad"
        id: 5
        invert: true
#      offset:
#        device: "gamepad"
#        id: 4


      twist_x:
        device: "gamepad"
        id: 6
      twist_y:
        device: "gamepad"
        id: 7
      twist_z:
        device: "gamepad"
        button_id_negative: 0
        button_id_positive: 3

      twist_yaw:
        device: "gamepad"
        id: 3
      twist_pitch:
        device: "gamepad"
        id: 4
        invert: true
      twist_roll:
        device: "gamepad"
        button_id_negative: 2
        button_id_positive: 1

    buttons:
      twist_mode:
        device: "gamepad"
        id: 4
      limit_on:
        device: "gamepad"
        id: 4
      limit_off:
        device: "gamepad"
        id: 4
      lock:
        device: "gamepad"
        id: 8
      unlock:
        device: "gamepad"
        id: 9


# trigger:
#   id: 0
# top down:
#   id: 1
# top left:
#   id: 2
# top right:
#   id: 0
