teleop_arm_joy_node:
  ros__parameters:
    joints:
      J1:
        max_speed: 1.0
      J2:
        max_speed: 1.0
      J3:
        max_speed: 1.0
      J4:
        max_speed: 1.0
      J5:
        max_speed: 1.0
      J6:
        max_speed: 1.0
    device_names: ["Left", "Right"]
    devices:
      Left:
        topic: "/joy_L"
      Right:
        topic: "/joy_R"
    axes:
      J1:
        device: "Left"
        id: 2
      J2:
        device: "Left"
        id: 0
      J3:
        device: "Left"
        id: 1
      J4:
        device: "Right"
        id: 1
        invert: true
      J5:
        device: "Right"
        id: 0
        invert: true
      J6:
        device: "Right"
        id: 2

      speed:
        device: "Right"
        id: 3
      offset:
        device: "Left"
        id: 3

      twist_x:
        device: "Right"
        id: 1
      twist_y:
        device: "Right"
        id: 0
      twist_z:
        device: ""
        id: 2

      twist_yaw:
        device: "Left"
        id: 1
      twist_pitch:
        device: "Left"
        id: 0
      twist_roll:
        device: "Left"
        id: 2

    buttons:
      twist_mode:
        device: "Right"
        id: 0
      limit_on:
        device: "Left"
        id: 4
      limit_off:
        device: "Left"
        id: 9
      lock:
        device: "Left"
        id: 5
      unlock:
        device: "Left"
        id: 8

# trigger:
#   id: 0
# top down:
#   id: 1
# top left:
#   id: 2
# top right:
#   id: 0
