teleop_science:
  ros__parameters:
    # The maximum rate at which updates should occur, and hence the max rate at which commands are sent.
    # Leaving this unset makes the max update rate unlimited.
    # update_rate: 50.0

    # The minimum rate at which updates occur.
    # Leaving this unset will allow for indefinite lapses between updates.
    # min_update_rate: 2.0

    control_modes:
      names: [
        # First in the list gets activated at startup
        "input_publisher_mode"
      ]

      # Declare types for the modes
      input_publisher_mode:
        display_name: "Input Publisher Control Mode"
        type: "input_publisher_mode/InputPublisherMode"
        active: true

    # Add lock and unlock commands
    commands:
      names:
        - lock
        - unlock
        - log_locked
        - log_unlocked

      lock:
        on_any:
          - "lock/down"
          - "start"
        type: set_button
        name: "locked"
        value: true
      unlock:
        on: "unlock/down"
        type: set_button
        name: "locked"
        value: false
      log_locked:
        on: "locked/down"
        type: log
        message: "Locked"
      log_unlocked:
        on: "locked/up"
        type: log
        message: "Unlocked"

input_publisher_mode:
  ros__parameters:
    input_names_topic: "/science/input"

    axis_names:
      # Auger
      - "auger_actuation"   # actuation for both the auger and the c-beam.
      - "auger_drill_speed"
      # Analysis Arm
      - "analysis_arm_actuation"
      # Tool Rotator
      - "tool_rotator_speed"
      # Chute
      - "chute_speed"
      # Sweeper
      - "sweeper_actuation"
      - "sweeper_speed"
    button_names:
      # Auger
      - "activate_auger"
      - "activate_cbeam"
      - "auger_drill"
      - "auger_drill_clockwise"
      - "auger_drill_anticlockwise"
      # Tool Rotator
      - "tool_rotator_twitch_decrease"
      - "tool_rotator_twitch_increase"
      - "tool_rotator_sweeper"
      - "tool_rotator_microscope"
      - "tool_rotator_nir_probe"
      # Chute
      - "chute_twitch_decrease"
      - "chute_twitch_increase"
      - "chute_engaged"
      - "chute_disengaged"
