



export default class EffectQueue<T extends unknown[]> {
  private queue: (((...args: T) => void) | undefined)[];

  // We can assert that this must be >= the length of queue.
  private nextFrameID: number;

  constructor() {
    this.queue = [];
    this.nextFrameID = 0;
  }

  public push(effect: (...args: T) => void): number {
    const frameID = this.nextFrameID;
    this.nextFrameID += 1;

    this.queue.push(effect);

    return frameID;
  }

  public cancel(frameID: number): void {
    const index = this.queue.length + frameID - this.nextFrameID;

    if (index < 0)
      return;

    if (index > this.queue.length) {
      console.error("EffectQueue.clear was given an index that wasn't generated by EffectQueue.push!");
      return;
    }

    this.queue[index] = undefined;
  }

  public clear(...args: T): boolean {
    if (this.queue.length === 0)
      return true;

    // Call every function in the queue
    for (let i = 0; i < this.queue.length; i++)
      this.queue[i]?.(...args);

    // Reset the queue
    this.queue = [];

    return false;
  }



}



