<?xml version="1.0"?>
<?xml-model href="http://download.ros.org/schema/package_format3.xsd" schematypens="http://www.w3.org/2001/XMLSchema"?>
<package format="3">
  <name>nova_behavior_tree</name>
  <version>0.0.0</version>
  <description>Behavior tree plugins and xml declarations for Monash Nova Rover</description>
  <maintainer email="novaroverteam@monash.edu">nova</maintainer>
  <license>BSD-3-Clause</license>

  <buildtool_depend>ament_cmake</buildtool_depend>

  <depend>behaviortree_cpp</depend>
  <depend>nav2_behavior_tree</depend>
  <depend>std_srvs</depend>
  <depend>geometry_msgs</depend>
  <depend>vision_msgs</depend>
  <depend>aruco_opencv_msgs</depend>
  <depend>tf2_ros</depend>
  <depend>nav2_util</depend>
  <depend>pluginlib</depend>
  <depend>rclcpp</depend>

  <test_depend>ament_lint_auto</test_depend>
  <test_depend>ament_lint_common</test_depend>

  <export>
    <build_type>ament_cmake</build_type>
  </export>
</package>
