# This is the schema for CAN Command Parameters
# This YAML will be converted to a python module
# Look here for docs about this YAML : https://github.com/PickNikRobotics/generate_parameter_library
can_command_parameters:
  logging_level:
    type: string
    default_value: "INFO"
    description: "Logging level."

  can_bus:
    type: string
    default_value: "can1"
    description: "CAN Bus to listen to."

  service:
    type: string
    default_value: ""
    description: "Service called to command this node to send a CAN message."

  commands:
    type: int_array
    default_value: [0] # empty array causes ros to think it's of type byte_array
    description: "List of commands that will cause this node to send a CAN command."

  command_names:
    type: string_array
    default_value: [""] # empty array causes ros to think it's of type byte_array
    description: "List human readable names of the command at the corresponding position."

  can_messages:
    type: string_array
    default_value: [""] # empty array causes ros to think it's of type byte_array
    description: "List of CAN commands to send when the node receives the command at the corresponding position."
