/pose_converter:
  ros__parameters:
    use_euler: false
    initial_base_link_quat:
      # x, y, z, qx, qy, qz, qw
      [-5., -5., 0., 0., 0., 0., 1.]
    initial_base_lin00k_euler:
      # x, y, z, yaw, pitch, roll
      [0., 0., 0., 3.927, 0., 0.]

/GRUC:
  ros__parameters:
    do_tank_turn: False

/goal_manager:
  ros__parameters:
    map_coords_cc:
      # x, y
      [10.0, 10.0, -10.0, 10.0, -10.0, -10.0, 10.0, -10.0]
    search_plan:
      # x, y
      [1.0, 3.0, -4.0, 3.0, -4.0, -3.0, 1.0, -3.0]
    tracked_tag_ids: [0, 1]
    tracked_block_colors: ["WHITE", "GREEN"]

/height_plane_mapper:
  ros__parameters:
    map_corners_coords:
      # x, y
      [10.0, 10.0, -10.0, 10.0, -10.0, -10.0, 10.0, -10.0]

/T265Node:
  ros__parameters:
    do_odometry: false
