controller_manager:
  ros__parameters:
    update_rate: 30
    use_sim_time: true

    wheel_velocity_controller:
      type: velocity_controllers/JointGroupVelocityController

    pivot_position_controller:
      type: position_controllers/JointGroupPositionController

    pivot_joint_trajectory_controller:
      type: joint_trajectory_controller/JointTrajectoryController

    #four_wheel_steering_controller:
    #  type: four_wheel_steering_controller/FourWheelSteeringController

        #four_steering_controller:
        #  type: four_steering_controller/FourSteeringController
    pivot_drive_controller:
      type: pivot_drive_controller/PivotDriveController

    diff_drive_controller:
      type: diff_drive_controller/DiffDriveController

    joint_broad:
      type: joint_state_broadcaster/JointStateBroadcaster

wheel_velocity_controller:
  ros__parameters:
    joints:
      - flw
      - blw
      - brw
      - frw

pivot_position_controller:
  ros__parameters:
    joints:
      - flp
      - blp
      - brp
      - frp

pivot_joint_trajectory_controller:
  ros__parameters:
    joints:
      - flp
      - blp
      - brp
      - frp
    
    command_interfaces:
      - position
      - velocity

    state_interfaces:
      - position
      - velocity

    allow_partial_joints_goal: true
    open_loop_control: true
    
four_wheel_steering_controller:
  ros__parameters:
    wheel_radius: 5.0
    wheel_track: 5.0
    wheelbase: 10.0
    y_steering_offset: 5.0

    #steering_controllers_library params
    reference_timeout: 0.1
    four_steering: true
    front_steering: false
    open_loop: false
    velocity_rolling_window_size: 10
    position_feedback: false
    use_stamped_vel: true
      #rear_wheels_names: ["brw", "blw"]
      #front_wheels_names: ["frw","flw"]
    wheels_names: ["blw", "brw", "flw", "frw"]
    steers_names: ["blp", "brp", "flp", "frp"]
    rear_wheels_state_names: ["blw", "brw"] 
    front_wheels_state_names: ["flw", "frw"]

four_steering_controller:
  ros__parameters:
    wheel_names: ["flw", "frw", "blw", "brw"]
    steer_names: ["flp", "frp", "blp", "brp"]
    enable_twist_cmd_: true
    wheel_steering_y_offset_: 0.0
    track_: 0.7
    wheel_base_: 0.84
    wheel_radius_: 0.15

pivot_drive_controller:
  ros__parameters:
    left_drive_names: ["flw", "blw"]
    right_drive_names: ["frw", "brw"]
    left_pivot_names: ["flp", "blp"]
    right_pivot_names: ["frp", "brp"]

diff_drive_controller:
  ros__parameters:
    left_wheel_names: ["flw", "blw"]
    right_wheel_names: ["frw", "brw"]
    position_feedback: false
    
    
  
