controller_manager:
  ros__parameters:
    update_rate: 10 
    use_sim_time: false

    wheel_velocity_controller:
      type: velocity_controllers/JointGroupVelocityController

    pivot_position_controller:
      type: position_controllers/JointGroupPositionController

    pivot_joint_trajectory_controller:
      type: joint_trajectory_controller/JointTrajectoryController

    joint_broad:
      type: joint_state_broadcaster/JointStateBroadcaster

wheel_velocity_controller:
  ros__parameters:
    joints:
      - flw

pivot_position_controller:
  ros__parameters:
    joints:
      - flp


joint_broad:
  ros__parameters:
    joints:
      - flp
      - flw
    

  
