/oak:
  ros__parameters:
    camera:
      i_nn_type: none
    rgb:
      i_fps: 5.0
    left:
      i_set_isp_scale: true
      i_fps: 5.0
    right:
      i_fps: 5.0
    stereo:
      i_align_depth: false
      i_enable_decimation_filter: true
      i_decimation_filter_decimation_factor: 4
      i_decimation_filter_decimation_mode: NON_ZERO_MEDIAN
      i_subpixel: true
      i_fps: 2.0