# Nintendo Pro Controller (Japanese Version)
teleop_drive_joy_node:
  ros__parameters:
    pivot_drive_controller:
      axis_linear_x: 1
      axis_angular_y: 2
    
    holonomic_drive_controller:
      axis_linear_x: 1
      axis_linear_y: 0
      axis_angular_y: 2
    
    strafe_controller:
      axis_linear_x: 0 # This might be incorrect
      axis_angular_y: 2
    
    nova_diff_drive_controller:
      axis_linear_x: 1
      axis_angular_y: 2
    
    button_pivot_drive_controller: 0
    button_holonomic_drive_controller: 1
    button_nova_diff_drive_controller: 2
    button_strafe_controller: 3
    axis_speed_change_fine: 4
    axis_speed_change_coarse: 5
    button_autonomous_control: 7
    button_manual_control: 8
    button_lock: 9
    button_unlock: 10
    speed_change_fine_val: -0.02 # DPad is Flipp'd on Japanese Version
