# Wired PDP Xbox Controller
teleop_drive_joy_node:
  ros__parameters:
    axis_linear_x: 1                       # Left Stick Vertical
    axis_linear_y: 0                       # Left Stick Horizontal
    axis_angular_z: 3                      # Right Stick Horizontal
    axis_linear_z: 4                       # Right Stick Vertical
    axis_speed_change_fine: 6              # DPad Left/Right
    axis_speed_change_coarse: 7            # DPad Up/Down
    
    button_pivot_drive_controller: 0       # Button A
    button_holonomic_drive_controller: 1   # Button B
    button_diff_drive_controller: 2   # Button X
    button_strafe_controller: 3            # Button Y
    button_autonomous_mode: 4
    button_manual_mode: 5
    button_lock: 6                         # Left Menu Button
    button_unlock: 7                       # Right Menu Button
