# Vanilla XBox Series X / S Controller
teleop_drive_joy_node:
  ros__parameters:
    controllers:
      [
        "pivot_drive_controller",
        "strafe_controller",
        "nova_diff_drive_controller",
      ]
    pivot_drive_controller:
      axis_linear_x: 1
      axis_angular_y: 3
      scale_linear_x: 0.1
      scale_angular_y: 1.0
    strafe_controller:
      axis_linear_x: 0
      axis_angular_y: 3
      scale_linear_x: 0.1
      scale_angular_y: 1.0
    nova_diff_drive_controller:
      axis_linear_x: 1
      axis_angular_y: 3
      scale_linear_x: 0.1
      scale_angular_y: 1.0
    axis_speed_change_coarse: 7
    axis_speed_change_fine: 6
    button_autonomous_control: 0
    button_lock: 6
    button_manual_control: 1
    button_nova_diff_drive_controller: 3
    button_pivot_drive_controller: 5
    button_strafe_controller: 4
    button_unlock: 7
    speed_change_coarse_val: 0.1
    speed_change_fine_val: 0.02
    speed_limit_max: 1.2
    speed_limit_min: 0.05
