# Vanilla XBox Series X / S Controller
teleop_drive_joy_node:
  ros__parameters:
    axis_linear_x: 1
    axis_linear_y: 0
    axis_linear_z: 2
    axis_angular_z: 3

    axis_speed_change_coarse: 7
    axis_speed_change_fine: 6
    button_lock: 6
    button_manual_control: 1
    button_nova_diff_drive_controller: 3
    button_pivot_drive_controller: 5
    button_strafe_controller: 4
    button_unlock: 7
    speed_change_coarse_val: 0.1
    speed_change_fine_val: 0.02
    speed_limit_max: 1.2
    speed_limit_min: 0.05
