#ifndef WARATAH_KINEMATICS_PLUGIN__VISIBILITY_CONTROL_H_
#define WARATAH_KINEMATICS_PLUGIN__VISIBILITY_CONTROL_H_

// This logic was borrowed (then namespaced) from the examples on the gcc wiki:
//     https://gcc.gnu.org/wiki/Visibility

#if defined _WIN32 || defined __CYGWIN__
#ifdef __GNUC__
#define WARATAH_KINEMATICS_PLUGIN_EXPORT __attribute__((dllexport))
#define WARATAH_KINEMATICS_PLUGIN_IMPORT __attribute__((dllimport))
#else
#define WARATAH_KINEMATICS_PLUGIN_EXPORT __declspec(dllexport)
#define WARATAH_KINEMATICS_PLUGIN_IMPORT __declspec(dllimport)
#endif
#ifdef WARATAH_KINEMATICS_PLUGIN_BUILDING_DLL
#define WARATAH_KINEMATICS_PLUGIN_PUBLIC WARATAH_KINEMATICS_PLUGIN_EXPORT
#else
#define WARATAH_KINEMATICS_PLUGIN_PUBLIC WARATAH_KINEMATICS_PLUGIN_IMPORT
#endif
#define WARATAH_KINEMATICS_PLUGIN_PUBLIC_TYPE WARATAH_KINEMATICS_PLUGIN_PUBLIC
#define WARATAH_KINEMATICS_PLUGIN_LOCAL
#else
#define WARATAH_KINEMATICS_PLUGIN_EXPORT __attribute__((visibility("default")))
#define WARATAH_KINEMATICS_PLUGIN_IMPORT
#if __GNUC__ >= 4
#define WARATAH_KINEMATICS_PLUGIN_PUBLIC __attribute__((visibility("default")))
#define WARATAH_KINEMATICS_PLUGIN_LOCAL __attribute__((visibility("hidden")))
#else
#define WARATAH_KINEMATICS_PLUGIN_PUBLIC
#define WARATAH_KINEMATICS_PLUGIN_LOCAL
#endif
#define WARATAH_KINEMATICS_PLUGIN_PUBLIC_TYPE
#endif

#endif // WARATAH_KINEMATICS_PLUGIN__VISIBILITY_CONTROL_H_
