/pose_converter:
  ros__parameters:
    use_euler: false
    initial_base_link_quat:
      # x, y, z, qx, qy, qz, qw
      [
        1., 1., 0., 0., 0., 1., 0.
      ]
    initial_base_link_euler:
      # x, y, z, yaw, pitch, roll
      [
        0., 0., 0., 0., 0., 0.
      ]

/GRUC:
  ros__parameters:
    do_tank_turn: False

/goal_manager:
  ros__parameters:
    search_plan:
      # x, y
      [
        2.0, 2.0,
        2.0, -2.0,
        -2.0, -2.0,
        -2.0, 2.0
      ]
    tracked_tag_ids:
      [
        0, 1, 2, 3, 4
      ]
    tracked_block_colors:
      [
        "RED", "GREEN", "YELLOW", "BLUE", "WHITE"
      ]
