# 
/autonomous_controller_node:
  ros__parameters:
    is_ARC: true
    search_coordinates:
      # x, y
      [
        -1.0, 1.1,
        8.0, -8.0,
        -8.0, -8.0,
        -8.0, 8.0
      ]
    tracked_tag_ids:
      [
        0, 1, 2, 3, 4
      ]
    tracked_block_colors:
      [
        "RED", "GREEN"
      ]
