controller_manager:
  ros__parameters:
    update_rate: 20
    use_sim_time: false

    nova_arm_velocity_controller:
      type: nova_arm_controller/NovaArmController

    nova_arm_position_controller:
      type: nova_arm_controller/NovaArmController

    nova_twistmapper:
      type: nova_twistmapper/NovaTwistmapper

    wheel_velocity_controller:
      type: velocity_controllers/JointGroupVelocityController

    pivot_position_controller:
      type: position_controllers/JointGroupPositionController

    pivot_joint_trajectory_controller:
      type: joint_trajectory_controller/JointTrajectoryController

    pivot_drive_controller:
      type: pivot_drive_controller/PivotDriveController

    strafe_controller:
      type: strafe_controller/StrafeController

    nova_diff_drive_controller:
      type: nova_diff_drive_controller/NovaDiffDriveController

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

nova_arm_velocity_controller:
  ros__parameters:
    joint_names:
      - arm_j1
      - arm_j2
      - arm_j3
      - arm_j4
      - arm_j5
      - arm_j6
    use_position_control: false
    use_collision_limits: false
    use_limits: false

nova_arm_position_controller:
  ros__parameters:
    joint_names:
      - arm_j1
      - arm_j2
      - arm_j3
      - arm_j4
      - arm_j5
      - arm_j6
    use_position_control: true
    use_collision_limits: false
    use_limits: false

nova_twistmapper:
  ros__parameters:
    chained_controller_name: "nova_arm_position_controller"
    joint_names:
      - arm_j1
      - arm_j2
      - arm_j3
      - arm_j4
      - arm_j5
      - arm_j6
    kinematics_solver: "kdl_kinematics_plugin/KDLKinematicsPlugin"
#    kinematics_solver: "banksia_kinematics_plugin/BanksiaKinematicsPlugin"

wheel_velocity_controller:
  ros__parameters:
    joints:
      - flw
      - blw
      - brw
      - frw

pivot_position_controller:
  ros__parameters:
    joints:
      - flp
      - blp
      - brp
      - frp

joint_state_broadcaster:
  ros__parameters:
    interfaces:
       ["position", "velocity"]

    joints:
      ["blp", "brp", "flp", "frp",
      "blw", "brw", "flw", "frw",
       "arm_j1", "arm_j2", "arm_j3", "arm_j4", "arm_j5", "arm_j6"]

    extra_joints:
      ["chassis_to_left_leg",
       "chassis_to_right_leg",
        "chassis_to_diffbar",
        "tl_ball_roll",
        "tl_ball_pitch",
        "tl_ball_yaw",
        "tr_ball_roll",
        "tr_ball_pitch",
        "tr_ball_yaw",
        "bl_ball_roll",
        "bl_ball_pitch",
        "bl_ball_yaw",
        "br_ball_roll",
        "br_ball_pitch",
        "br_ball_yaw"]
    use_local_topics: false
    
pivot_drive_controller:
  ros__parameters:
    enable_twist_cmd: true
    left_drive_names: ["flw", "blw"]
    right_drive_names: ["frw", "brw"]
    left_pivot_names: ["flp", "blp"]
    right_pivot_names: ["frp", "brp"]
    open_loop: false
    has_velocity_limits: true
    has_acceleration_limits: true
    max_velocity: 2.794144
    min_velocity: -2.794144 
    max_acceleration: 0.1
    min_acceleration: -0.1
    twist_covariance_diagonal: [0.1, 0.1, 0.1, 0.1, 0.1, 0.1]

strafe_controller:
  ros__parameters:
    enable_twist_cmd: true
    left_drive_names: ["flw", "blw"]
    right_drive_names: ["frw", "brw"]
    left_pivot_names: ["flp", "blp"]
    right_pivot_names: ["frp", "brp"]
    open_loop: true
    max_acceleration: 5.0

nova_diff_drive_controller:
  ros__parameters:
    enable_twist_cmd: true
    left_drive_names: ["flw", "blw"]
    right_drive_names: ["frw", "brw"]
    left_pivot_names: ["flp", "blp"]
    right_pivot_names: ["frp", "brp"]
    wheels_per_side: 2
    linear:
      x:
        max_acceleration: 5.0
    twist_covariance_diagonal: [0.1, 0.1, 0.1, 0.1, 0.1, 0.1]

