export default class EffectQueue<T extends unknown[]> {
  private queue: (((...args: T) => void) | undefined)[];

  // We can assert that this must be >= the length of queue.
  private nextFrameID: number;

  constructor() {
    this.queue = [];
    this.nextFrameID = 0;
  }

  protected get length() {
    return this.queue.length;
  }

  /**
   * Adds an effect callback function to the queue
   * @param effect The function to run when the queue is cleared
   * @returns an integer that identifies the effect, which can be passed to this.cancel to prevent the effect function
   * from running if it has not already been run
   */
  public push(effect?: (...args: T) => void): number {
    if (!effect) {
      // Allow pushing nothing to trigger this.clear
      if (this.queue.length === 0)
        this.queue.push(undefined);
      return -1;
    }

    const frameID = this.nextFrameID;
    this.nextFrameID += 1;

    this.queue.push(effect);

    return frameID;
  }

  /**
   * Given some value returned from a call of this.push, prevents the given effect from running if it has not already
   * been executed.
   * @param frameID the returned value for some call of this.push
   */
  public cancel(frameID: number): void {
    const index = this.queue.length + frameID - this.nextFrameID;

    if (index < 0)
      return;

    if (index > this.queue.length) {
      console.error("EffectQueue.clear was given an index that wasn't generated by EffectQueue.push!");
      return;
    }

    this.queue[index] = undefined;
  }

  /**
   * Runs all functions currently present in the queue, passing along the arguments given to the functions in the queue.
   * @param args the arguments to pass to the functions in the queue when executing them
   */
  public clear(...args: T): boolean {
    if (this.queue.length === 0)
      return true;

    // Call every function in the queue
    for (let i = 0; i < this.queue.length; i++)
      this.queue[i]?.(...args);

    // Clear the queue
    this.queue = [];

    return false;
  }
}
