keyboard_localiser:
  ros__parameters:
    # using auto or manual transform mode
    using_auto: false
    debug_image: true
    # key position initalisation params
    keyboard_frame: keyboard_frame
    base_frame: arm_link

    # (manual) keyboard alignment params
    aligned_keyboard_position: [0.0,-1.0,0.5]
    aligned_keyboard_quaternion: [6.1327e-06, 0.70713, -0.70708, 3.5358e-06] #[0.0,0.0,-0.7071081,0.7071055]
    # relative to base_frame

    # calibrated camera intrinsics
    hfov: 61.3727248
    image_width: 640 #1280
    image_height: 480 #720
    distortion_matrix: [0.59680899,-2.13821558,-0.01071933,0.0900803,4.94332294]

    # OpenCV filter params
    dark_threshold: 120 # 0-255
    kernel_size: 100

    # (auto) keyboard pose analysis initalisation
    camera_frame: arm_end_periscope_optical

    # tf2 initalisation
    tf_publish_rate: 1.0 # per second

typing_sequencer:
  ros__parameters:
    # key position initalisation params
    keyboard_frame: keyboard_frame
    base_frame: arm_kinematics_origin # old arm = arm_link # new arm = arm_kinematics_origin
    ee_frame: endeffector_kinematics
    actuator_frame: actuator

    timeout: 2.0
    pollrate: 10.0

    # path planner movement
    speed: 0.01 # m/s
    debug_target: True