# ==========================================================
# Monash Nova Rover
# Excavation and Construction – Default Parameter File
# ==========================================================

scraper:
  ros__parameters:
    can_bus: "can0"
    update_rate: 10
    controllers:
      controller:
        minimum_speed: 0.05
    hardware:
      arm:
        can_id: 0xC1
        max_effort: 1.0
        reversed: true
      scoop:
        can_id: 0xD1
        max_effort: 1.0
        reversed: false
      claw:
        can_id: 0xC2
        max_effort: 0.6
        reversed: true

tile_placer:
  ros__parameters:
    can_bus: "can0"
    update_rate: 10
    controllers:
      controller:
        minimum_speed: 0.05
    hardware:
      forklift:
        can_id: 0xD2
        max_effort: 0.7
        reversed: false