gps_base:
  ros__parameters:
    baudrate: 115200
    # UM960
    port_name: /dev/serial/by-id/usb-1a86_USB_Serial-if00-port0
    port_type: USB
    svin: true

gps_rover:
  ros__parameters:
    baudrate: 115200
    # UM982
    port_name: /dev/serial/by-id/usb-1a86_USB_Serial-if00-port0
    publisher_rate: 20

magnetometer:
  ros__parameters:
    bus: 7
    addr: 0x1E
