# ==========================================================
# Monash Nova Rover
# GPS Rover – Default Parameter File
# ==========================================================

/gps_rover:
  ros__parameters:
    baudrate: 115200
    port_name: /dev/i2c-4
    publisher_rate: 20
    protocol: nmea

/drone_gps_rover:
  ros__parameters:
    baudrate: 230400
    port_name: /dev/ttyTHS1
    publisher_rate: 20
    protocol: ubx