# Nintendo Pro Controller (Japanese Version)
teleop_drive_joy_node:
  ros__parameters:
    controllers:
      [
        "pivot_drive_controller",
        "strafe_controller",
        "nova_diff_drive_controller",
      ]
    pivot_drive_controller:
      axis_angular_z: 2
      axis_linear_x: 1
      scale_angular_z: 0.85
      scale_linear_x: 0.1
    strafe_controller:
      axis_angular_z: 2
      axis_linear_x: 0 # This might be incorrect
      scale_angular_z: 1.0
      scale_linear_x: 0.1
    nova_diff_drive_controller:
      axis_angular_z: 2
      axis_linear_x: 1
      scale_angular_z: 1.0
      scale_linear_x: 0.1
    axis_speed_change_coarse: 5
    axis_speed_change_fine: 4
    button_autonomous_control: 0
    button_lock: 9
    button_manual_control: 1
    button_nova_diff_drive_controller: 4
    button_pivot_drive_controller: 7
    button_strafe_controller: 6
    button_unlock: 10
    speed_change_coarse_val: 0.1
    speed_change_fine_val: -0.02 # DPad is Flipp'd on Japanese Version
    speed_limit_max: 1.2
    speed_limit_min: 0.05
