bt_navigator:
  ros__parameters:
    global_frame: map
    robot_base_frame: base_link
    odom_topic: /odometry/global 
    bt_loop_duration: 30
    default_server_timeout: 60000
    wait_for_service_timeout: 1000
    action_service_result_timeout: 900.0
    goal_reached_tol: 1.0
    goal_offset_radius: 0.7
    # sqrt((wheel_base / 2 + wheel_radius)^2 + (steering_track / 2 + wheel_radius)^2)
    robot_radius: 0.85
    error_code_names:
      - compute_path_error_code
      - follow_path_error_code
    navigators: ["navigate_to_pose", "navigate_through_poses", "urc_2025_navigator"]
    navigate_to_pose:
      plugin: "nav2_bt_navigator::NavigateToPoseNavigator"
    navigate_through_poses:
      plugin: "nav2_bt_navigator::NavigateThroughPosesNavigator"
    default_nav_through_poses_bt_xml: /home/nova/nova/src/ros/rover/auto/nova_behavior_tree/behavior_tree/test/navigate_through_poses_w_replanning_and_recovery.xml
    urc_2025_navigator:
      plugin: "nova_bt_navigators::URC2025Navigator"
    default_urc_2025_navigator_bt_xml: /home/nova/nova/src/ros/rover/auto/nova_behavior_tree/behavior_tree/test/navigate_through_poses_w_replanning_and_recovery.xml
    plugin_lib_names:
      # ACTION NODES
      - nova_place_search_goals_action_bt_node
      - nova_get_goal_action_bt_node
      - nova_blackboard_publisher_bt_node
      - nova_led_service_bt_node
      - nova_remove_passed_urc_goals_action_bt_node
      - nova_update_urc_goals_action_bt_node
      - nova_snap_in_collision_goals_action_bt_node
      - nova_get_current_pose_action_bt_node
      # CONDITION NODES
      - nova_ar_tag_detected_condition_bt_node
      - nova_enable_detection_condition_bt_node
      - nova_object_detected_condition_bt_node

bt_navigator_navigate_through_poses_rclcpp_node:
  ros__parameters:
    use_sim_time: False

bt_navigator_navigate_to_pose_rclcpp_node:
  ros__parameters:
    use_sim_time: False
