#!/usr/bin/env python3

"""
DISCLAIMER: This script was generated by AI, but has been tested and verified to work correctly.
"""

import numpy as np
import rclpy
from rclpy.node import Node
from sensor_msgs.msg import PointCloud2, PointField

# Packed output dtype matching the Livox Mid-360 PointCloud2 field layout (26 bytes/point)
_OUT_DTYPE = np.dtype({
    'names':   ['x',   'y',   'z',   'intensity', 'tag', 'line', 'timestamp'],
    'formats': ['<f4', '<f4', '<f4', '<f4',       'u1',  'u1',   '<f8'],
    'offsets': [0,     4,     8,     12,           16,    17,     18],
    'itemsize': 26,
})

_SCAN_PERIOD_NS = 0.1 * 1e9  # 10 Hz LiDAR scan period in nanoseconds
_DEFAULT_TAG = 0x10


class LivoxFieldRepublisher(Node):
    """Republish PointCloud2 into a Livox Mid-360 field layout.

    Output layout per point (26 bytes):
      x: float32 (offset 0)
      y: float32 (offset 4)
      z: float32 (offset 8)
      intensity: float32 (offset 12)
      tag: uint8 (offset 16)
      line: uint8 (offset 17)
      timestamp: float64 (offset 18)
    """

    def __init__(self) -> None:
        super().__init__("livox_field_republisher")

        self.declare_parameter("input_topic", "/livox/lidar_sim")
        self.declare_parameter("output_topic", "/livox/lidar")

        input_topic = self.get_parameter("input_topic").get_parameter_value().string_value
        output_topic = self.get_parameter("output_topic").get_parameter_value().string_value

        self.pub = self.create_publisher(PointCloud2, output_topic, 10)
        self.sub = self.create_subscription(PointCloud2, input_topic, self.cb, 10)

        self.get_logger().info(
            f"Republishing PointCloud2 from {input_topic} to {output_topic} with Livox-like fields"
        )

    @staticmethod
    def _extract(buf: np.ndarray, offset: int, n: int, step: int,
                 nbytes: int, np_type: str) -> np.ndarray:
        """Vectorised strided field extraction: n values of nbytes at offset + i*step."""
        col_idx = np.add.outer(
            offset + np.arange(n, dtype=np.intp) * step,
            np.arange(nbytes, dtype=np.intp),
        )  # shape (n, nbytes)
        return buf[col_idx].reshape(-1).view(np_type)

    def cb(self, msg: PointCloud2) -> None:
        fmap = {f.name: f for f in msg.fields}
        missing = [name for name in ('x', 'y', 'z') if name not in fmap]
        if missing:
            self.get_logger().error(f"Missing required fields in input cloud: {missing}")
            return

        n = msg.width * msg.height
        step = msg.point_step
        ft = '>' if msg.is_bigendian else '<'
        buf = np.frombuffer(msg.data, dtype=np.uint8)

        x = self._extract(buf, fmap['x'].offset, n, step, 4, f'{ft}f4')
        y = self._extract(buf, fmap['y'].offset, n, step, 4, f'{ft}f4')
        z = self._extract(buf, fmap['z'].offset, n, step, 4, f'{ft}f4')

        valid = np.isfinite(x) & np.isfinite(y) & np.isfinite(z)
        n_valid = int(valid.sum())
        orig_idx = np.where(valid)[0]

        out_arr = np.empty(n_valid, dtype=_OUT_DTYPE)
        out_arr['x'] = x[valid]
        out_arr['y'] = y[valid]
        out_arr['z'] = z[valid]

        if 'intensity' in fmap:
            out_arr['intensity'] = self._extract(
                buf, fmap['intensity'].offset, n, step, 4, f'{ft}f4')[valid]
        else:
            out_arr['intensity'] = 0.0

        if 'tag' in fmap:
            out_arr['tag'] = buf[fmap['tag'].offset::step][:n][valid]
        else:
            out_arr['tag'] = _DEFAULT_TAG

        out_arr['line'] = (orig_idx // msg.width).astype(np.uint8) if msg.height > 1 else np.uint8(0)

        if 'timestamp' in fmap:
            out_arr['timestamp'] = self._extract(
                buf, fmap['timestamp'].offset, n, step, 8, f'{ft}f8')[valid]
        elif 't' in fmap:
            out_arr['timestamp'] = self._extract(
                buf, fmap['t'].offset, n, step, 4, f'{ft}u4')[valid].astype(np.float64)
        else:
            header_ns = float(msg.header.stamp.sec) * 1e9 + float(msg.header.stamp.nanosec)
            dt_ns = _SCAN_PERIOD_NS / float(max(n - 1, 1))
            out_arr['timestamp'] = header_ns + dt_ns * orig_idx.astype(np.float64)

        out = PointCloud2()
        out.header     = msg.header
        out.height     = 1
        out.width      = n_valid
        out.is_bigendian = msg.is_bigendian
        out.is_dense   = True
        out.fields     = [
            PointField(name='x',         offset=0,  datatype=PointField.FLOAT32, count=1),
            PointField(name='y',         offset=4,  datatype=PointField.FLOAT32, count=1),
            PointField(name='z',         offset=8,  datatype=PointField.FLOAT32, count=1),
            PointField(name='intensity', offset=12, datatype=PointField.FLOAT32, count=1),
            PointField(name='tag',       offset=16, datatype=PointField.UINT8,   count=1),
            PointField(name='line',      offset=17, datatype=PointField.UINT8,   count=1),
            PointField(name='timestamp', offset=18, datatype=PointField.FLOAT64, count=1),
        ]
        out.point_step = 26
        out.row_step   = 26 * n_valid
        out.data       = out_arr.tobytes()
        self.pub.publish(out)


def main(args=None) -> None:
    rclpy.init(args=args)
    node = LivoxFieldRepublisher()
    try:
        rclpy.spin(node)
    finally:
        node.destroy_node()
        rclpy.shutdown()


if __name__ == "__main__":
    main()
