# teleop.yaml
teleop_arm:
  ros__parameters:
    # The maximum rate at which updates should occur, and hence the max rate at which commands are sent.
    # Leaving this unset makes the max update rate unlimited.
    # update_rate: 50.0

    # The minimum rate at which updates occur.
    # Leaving this unset will allow for indefinite lapses between updates.
    min_update_rate: 2.0

    input_sources:
      names: [
        "joy_input_source"
      ]

      # Then declare its type!
      joy_input_source:
        type: "teleop_modular_joy/JoyInputSource"

    control_modes:
      names: [
        "joint_space_mode",
        "task_space_mode"
      ]

      # Then declare its type!
      joint_space_mode:
        type: "joint_space_control_mode/JointSpaceControlMode"
      task_space_mode:
        type: "teleop_modular_twist/TwistControlMode"

    commands:
      names: [
        "enter_task_space",
        "enter_joint_space"
      ]

      enter_task_space_mode:
        on: "task_space/down"
        type: "activate_control_mode"
        name: "task_space_mode"
      enter_joint_space_mode:
        on: "task_space/up"
        type: "activate_control_mode"
        name: "joint_space_mode"


joint_space_mode:
  ros__parameters:
    topic: "/arm_fk_velocity_target"
    joints:
      1:
        name: "j1"
        input_name: "j1"
        scale: 0.36
      2:
        name: "j2"
        input_name: "j2"
        scale: 0.36
      3:
        name: "j3"
        input_name: "j3"
        scale: 0.36
      4:
        name: "j4"
        input_name: "j4"
        scale: 0.36
      5:
        name: "j5"
        input_name: "j5"
        scale: 0.36
      6:
        name: "j6"
        input_name: "j6"
        scale: 0.36


task_space_mode:
  ros__parameters:
    # Topic to send TwistStamped messages to.
    stamped_topic: "/arm_ik_twist_stamped"
    # Use the input named "speed" to scale everything.
    use_speed_input: true

    # Values to multiply inputs with.
    scale:
      linear:
        all: 0.25
      angular:
        all: 0.785398163395

    # Prevent velocities larger than the specified values from being emitted
    limits:
      linear:
        all: 0.25
        normalized: true
        scale_with_speed: true
      angular:
        all: 0.785398163395
        normalized: true
        scale_with_speed: true


joy_input_source:
  ros__parameters:
    topic: "/joy"
    # These are the default mappings for a game_controller_node.
    # https://docs.ros.org/en/ros2_packages/rolling/api/joy/index.html
    # If you use joy_node, you'll need to figure out what the mapping is yourself.
    # So, run joy, `ros2 topic echo /joy`, and mess around with your controller to figure out what it is for you.
    button_definitions: [
      "A",
      "B",
      "X",
      "Y",
      "BACK",
      "GUIDE",
      "START",
      "LEFTSTICK",
      "RIGHTSTICK",
      "LEFTSHOULDER",
      "RIGHTSHOULDER",
      "DPAD_UP",
      "DPAD_DOWN",
      "DPAD_LEFT",
      "DPAD_RIGHT",
      "MISC1",
      "PADDLE1",
      "PADDLE2",
      "PADDLE3",
      "PADDLE4",
      "TOUCHPAD"
    ]
    axis_definitions: [
      "LEFTX",
      "LEFTY",
      "RIGHTX",
      "RIGHTY",
      "TRIGGERLEFT",
      "TRIGGERRIGHT"
    ]

    # TODO: remapping