# teleop.yaml
teleop_arm:
  ros__parameters:
    # The maximum rate at which updates should occur, and hence the max rate at which commands are sent.
    # Leaving this unset makes the max update rate unlimited.
    update_rate: 50.0

    # The minimum rate at which updates occur.
    # Leaving this unset will allow for indefinite lapses between updates.
    min_update_rate: 2.0

    controller_manager: "/arm/controller_manager"

    control_modes:
      names:
        - joint_space_mode
        - task_space_mode
        - end_effector_mode

      joint_space_mode:
        display_name: "Joint Space"
        type: "joint_space_control_mode/JointSpaceControlMode"
        active: true
        controllers:
          - nova_arm_velocity_controller

      task_space_mode:
        display_name: "Task Space (IK)"
        type: "teleop_modular_twist/TwistControlMode"
        controllers:
          - "nova_twistmapper"
          - "nova_arm_position_controller"

      end_effector_mode:
        display_name: "End Effector"
        type: "joint_space_control_mode/JointSpaceControlMode"
        active: true
        controllers:
          - nova_end_effector_velocity_controller

    commands:
      names:
        - enter_task_space
        - enter_joint_space
        - lock
        - unlock
        - log_locked
        - log_unlocked

      enter_task_space:
        on: "task_space/down"
        type: switch_control_mode
        activate:
          - "task_space_mode"
        deactivate:
          - "joint_space_mode"
      enter_joint_space:
        on_any:
          - "task_space/up"
        type: switch_control_mode
        activate:
          - "joint_space_mode"
        deactivate:
          - "task_space_mode"

      lock:
        on_any:
          - "lock/down"
          - "start"
        type: set_button
        name: "locked"
        value: true
      unlock:
        on: "unlock/down"
        type: set_button
        name: "locked"
        value: false
      log_locked:
        on: "locked/down"
        type: log
        message: "Locked"
      log_unlocked:
        on: "locked/up"
        type: log
        message: "Unlocked"

end_effector_mode:
  ros__parameters:
    topic: "/arm/end_effector_joint_velocity_command"
    use_speed_input: false

    joint_definitions:
      - actuator_head
      - left_slide

    joints:
      actuator_head:
        name: "actuator_head"
        input_name: "actuator_head"
        scale: 0.1
      left_slide:
        name: "left_slide"
        input_name: "left_slide"
        scale: 0.1

joint_space_mode:
  ros__parameters:
    topic: "/arm/joint_velocity_command"
    use_speed_input: true

    joint_definitions:
      - "j1"
      - "j2"
      - "j3"
      - "j4"
      - "j5"
      - "j6"
    joints:
      j1:
        name: "J1"
        input_name: "j1"
        scale: 0.1
      j2:
        name: "J2"
        input_name: "j2"
        scale: 0.1
      j3:
        name: "J3"
        input_name: "j3"
        scale: 0.1
      j4:
        name: "J4"
        input_name: "j4"
        scale: 0.25
      j5:
        name: "J5"
        input_name: "j5"
        scale: 0.1
      j6:
        name: "J6"
        input_name: "j6"
        scale: 0.36

task_space_mode:
  ros__parameters:
    # Topic to send TwistStamped messages to.
    stamped_topic: "/arm/task_space_twist_command"
    # Use the input named "speed" to scale everything.
    use_speed_input: false

    # Values to multiply inputs with.
    scale:
      linear:
        all: 0.125
      angular:
        all: 0.785398163395

    # Prevent velocities larger than the specified values from being emitted
    limits:
      linear:
        all: 0.1
        normalized: true
        scale_with_speed: true
      angular:
        all: 0.2
        normalized: true
        scale_with_speed: true


