# teleop.yaml
teleop_arm:
  ros__parameters:
    # The maximum rate at which updates should occur, and hence the max rate at which commands are sent.
    # Leaving this unset makes the max update rate unlimited.
    # update_rate: 50.0

    # The minimum rate at which updates occur.
    # Leaving this unset will allow for indefinite lapses between updates.
    min_update_rate: 4.0

    input_sources:
      names:
        - joy_input_source

      # Then declare its type!
      joy_input_source:
        type: "teleop_modular_joy/JoyInputSource"

    control_modes:
      names:
        - joint_space_mode
        - task_space_mode

      # Then declare its type!
      joint_space_mode:
        type: "joint_space_control_mode/JointSpaceControlMode"
        controllers:
          - nova_arm_velocity_controller

      task_space_mode:
        type: "teleop_modular_twist/TwistControlMode"
        controllers:
          - nova_arm_position_controller
          - nova_twistmapper

    commands:
      names:
        - enter_task_space
        - enter_joint_space

      enter_task_space:
        on: "task_space/down"
        type: switch_control_mode
        to: task_space_mode
      enter_joint_space:
        on: "task_space/up"
        type: switch_control_mode
        to: joint_space_mode
      lock:
        on_any: ["lock/down", "start"]
        type: set_button
        name: locked
        value: true
      unlock:
        on: "unlock/up"
        type: set_button
        name: locked
        value: false
      log_locked:
        on: "locked/down"
        type: log
        message: "Locked"
      log_unlocked:
        on: "locked/down"
        type: log
        message: "Unlocked"


joint_space_mode:
  ros__parameters:
    topic: "/arm_fk_velocity_target"
    use_speed_input: true

    joint_definitions:
      - j1
      - j2
      - j3
      - j4
      - j5
      - j6

    joints:
      j1:
        name: "J1"
        input_name: "j1"
        scale: 0.1001
      j2:
        name: "J2"
        input_name: "j2"
        scale: 0.1001
      j3:
        name: "J3"
        input_name: "j3"
        scale: 0.1001
      j4:
        name: "J4"
        input_name: "j4"
        scale: 0.1001
      j5:
        name: "J5"
        input_name: "j5"
        scale: 0.1001
      j6:
        name: "J6"
        input_name: "j6"
        scale: 0.1001


task_space_mode:
  ros__parameters:
    # Topic to send TwistStamped messages to.
    stamped_topic: "/arm_ik_twist_stamped"
    # Use the input named "speed" to scale everything.
    use_speed_input: true

    # Values to multiply inputs with.
    scale:
      linear:
        all: 0.05
      angular:
        all: 0.05

    # Prevent velocities larger than the specified values from being emitted
    limits:
      linear:
        all: 0.05
        normalized: true
        scale_with_speed: true
      angular:
        all: 0.05
        normalized: true
        scale_with_speed: true


joy_input_source:
  ros__parameters:
    topic: "/joy"
    # These are the default mappings for a game_controller_node.
    # https://docs.ros.org/en/ros2_packages/rolling/api/joy/index.html
    # If you use joy_node, you'll need to figure out what the mapping is yourself.
    # So, run joy, `ros2 topic echo /joy`, and mess around with your controller to figure out what it is for you.
    button_definitions:
      - "A"
      - "B"
      - "X"
      - "Y"
      - BACK
      - GUIDE
      - START
      - LEFTSTICK
      - RIGHTSTICK
      - LEFTSHOULDER
      - RIGHTSHOULDER
      - DPAD_UP
      - DPAD_DOWN
      - DPAD_LEFT
      - DPAD_RIGHT
      - MISC1
      - PADDLE1
      - PADDLE2
      - PADDLE3
      - PADDLE4
      - TOUCHPAD
    axis_definitions:
      - LEFTX
      - LEFTY
      - RIGHTX
      - RIGHTY
      - TRIGGERLEFT
      - TRIGGERRIGHT

    remap:
      axes:
        speed:
          from: TRIGGERRIGHT
          invert: true

        # Joint space
        j1:
          from_buttons:
            positive: DPAD_RIGHT
            negative: DPAD_LEFT
          invert: true
        j2:
          from_buttons:
            positive: DPAD_UP
            negative: DPAD_DOWN
          invert: true
        j3:
          from_buttons:
            positive: "Y"
            negative: "A"
        j4:
          from: RIGHTY
          invert: true
        j5:
          from: RIGHTX
        j6:
          from_buttons:
            positive: "X"
            negative: "B"

        # Task space
        linear:
          x:
            from_buttons:
              positive: DPAD_UP
              negative: DPAD_DOWN
          y:
            from_buttons:
              positive: DPAD_RIGHT
              negative: DPAD_LEFT
          z:
            from_buttons:
              positive: "Y"
              negative: "A"
        angular:
          x:
            from_buttons:
              positive: "X"
              negative: "B"
          y:
            from: RIGHTY
            invert: true
          z:
            from: RIGHTX

      buttons:
        lock:
          from: BACK
        unlock:
          from: START
        task_space:
          from: LEFTSHOULDER