#BLCMDTelemetry used to give telemetry from the blcmds

# The Bus Index of the CMD
string bus

# The CMD Index that is being used
int8 id

# The rotor velocity in rad/s
float64 rotor_velocity

# The q_current in A
float64 q_current

# The rotor interval
float64 rotor_interval

# The D Current in A
float64 d_current

# The resolver position
float64 resolver_position

# The resolver velocity
float64 resolver_velocity

# The power in W
float64 power

# The voltage in V
float64 voltage

# The temperature in C
float64 temperature

