# Ros2 service message type for setting the LED colour
# on the back of the rover for URC.
# Only one colour should be non-zero. Value gives intensity from 0-255
uint8 r
uint8 g
uint8 b
uint8 intensity
---
bool sent_status
