can_number_listener_parameters:
  initial_value:
    type: double
    default_value: 0
    description: "Initial value of the listener."

  length:
    type: int
    default_value: 2
    description: "Length of expected data in message in bytes (two hex digits). Does not include command IDs."

  scale:
    type: double
    default_value: 1
    description: "Constant coefficient to be applied to the received CAN message data when calculating the output."

  offset:
    type: double
    default_value: 0
    description: "Constant offset to be applied to the received CAN message data when calculating the output."
