self: super:

{
  rosPackages = super.rosPackages.appendDistroOverlay
    (rosSelf: rosSuper: {
      # Package definitions generated by Super Flore are given a "ros-${distro}-" name prefix.
      # This is useful for manually-defined packages too, so add it in if it's missing.
      buildRosPackage =
        let
          distroPrefix = "ros-${rosSelf.ros-environment.rosDistro}-";
          addDistroPrefix = name: if self.lib.hasPrefix distroPrefix name then name else distroPrefix + name;
        in
        args: rosSuper.buildRosPackage (args
          // self.lib.optionalAttrs (args ? pname) { pname = addDistroPrefix args.pname; }
          // self.lib.optionalAttrs (args ? name) { name = addDistroPrefix args.name; }
        );
    })
    super.rosPackages;
}
