# Used to move the hydraprobe to specified position

# enum for the command
byte RESET = 0
byte MOVE_UP = 1
byte MOVE_DOWN = 2

byte command

---

# Each action could fail. This flag shows the output success of the action
bool success
