string port
uint8 filter_select
uint8 laser_colour
uint8 stepper_angle
uint8 mirror_angle
uint8 pump_mode
uint32 SH_period
uint32 ICG_period
uint8 average
bool collection_mode_single
---
uint16[] spectra