# This is only the schema for Node Parameters
# This YAML will be converted to teleop_drive_joy_parameters.hpp upon build
# Look at individual controller config for changing axes / buttons
# Look here for docs about this YAML : https://github.com/PickNikRobotics/generate_parameter_library
teleop_drive_joy:
  input_topic: { type: string, default_value: "/joy", description: "Input Topic for Joy Messages" }
  output_topic: { type: string, default_value: "/cmd_vel", description: "Output Topic for Twist Commands" }
  
  button_debounce_time:
    type: int
    default_value: 200
    description: "Debounce Time for Joy Messages in Milliseconds"

  initial_speed:
    type: double
    default_value: 0.1
    description: "Initial Speed of the Rover when Teleop is started"

  controllers:
    type: string_array
    default_value:
      [
        "pivot_drive_controller",
        "holonomic_drive_controller",
        "strafe_controller",
        "nova_diff_drive_controller",
      ]
    description: "List Of Controllers that can be used with teleop"
    read_only: true
  
  __map_controllers:
    axis_linear_x:
      {
        type: int,
        default_value: 1,
        description: "The Axis controlling linear velocity. Usually refers to the Left Stick Verical Axis",
      }
    axis_linear_y:
      {
        type: int,
        default_value: 0,
        description: "The Axis controlling lateral velocity. Usually refers to the Left Stick Horizontal Axis",
      }
    axis_angular_y:
      {
        type: int,
        default_value: 3,
        description: "The Axis controlling angular velocity. Usually refers to the Right Stick Horizontal Axis",
      }
    scale_angular:
      {
        type: double,
        default_value: 1,
        description: "A scale parameter applied on angular velocity",
      }

  button_unlock: { type: int, default_value: 9, description: "Unlock Gamepad" }

  button_lock: { type: int, default_value: 10, description: "Lock Gamepad" }

  button_strafe_controller:
    { type: int, default_value: 6, description: "Switch to Strafe Mode" }

  button_holonomic_drive_controller:
    { type: int, default_value: 5, description: "Switch to Holonomic Mode" }

  button_pivot_drive_controller:
    { type: int, default_value: 7, description: "Switch to Pivot Mode" }

  button_nova_diff_drive_controller:
    { type: int, default_value: 4, description: "Switch to Tank Mode" }

  axis_speed_change_fine:
    {
      type: int,
      default_value: 6,
      description: "Axis to increment current speed on a coarse scale. This is usually mapped to DPad Horizontal",
    }

  axis_speed_change_coarse:
    {
      type: int,
      default_value: 7,
      description: "Axis to increment current speed on a coarse scale. This is usually mapped to DPad Vertical",
    }

  speed_change_coarse_val:
    {
      type: double,
      default_value: 0.1,
      description: "Value to change speed when the speed_change_coarse is invoked",
    }

  speed_change_fine_val:
    {
      type: double,
      default_value: 0.02,
      description: "Value to change speed when the speed_change_fine is invoked",
    }

  # 1.0 = 100% max linear velocity, 0.5 = 50% max linear velocity, etc.
  # Max linear velocity is defined by the controller e.g. pivot_drive_controller
  speed_limit_max:
    {
      type: double,
      default_value: 1.0,
      description: "Factor to limit the maximum speed of the Rover",
    }

  speed_limit_min:
    {
      type: double,
      default_value: 0.05,
      description: "Factor to limit the minimum speed of the Rover",
    }
