# This is only the schema for Node Parameters
# This YAML will be converted to teleop_drive_joy_parameters.hpp upon build
# Look at individual controller config for changing axes / buttons
# Look here for docs about this YAML : https://github.com/PickNikRobotics/generate_parameter_library
teleop_arm_joy:
  devices:
    type: string_array
    default_value: [
      "Left",
      "Right"
    ]

  axis_definitions:
    type: string_array
    default_value: [
      "j1",
      "j2",
      "j3",
      "j4",
      "j5",
      "j6",
      "speed",
      "offset"
    ]
    description: "The list of mappable axes."
    read_only: true

  button_definitions:
    type: string_array
    default_value: [
      "limit_on",
      "limit_off",
      "lock",
      "unlock"
    ]
    description: "The list of mappable axes."
    read_only: true

  device_mappings:
    __map_devices:
      topic:
        type: string
        description: "The topic to get sensor_msgs/msg/Joy messages from for this device"
      axes:
        __map_axis_definitions:
          id:
            type: int
      buttons:
        __map_button_definitions:
          id:
            type: int







#  controllers:
#    type: string_array
#    default_value: []
#    description: "The list of controllers that can be used with arm teleop."
#    read_only: true
#  __map_controllers:

