# For correcting absolute errors in GPS readings. At the start of autonomous,
# send the GPS coordinate of the start truth. This will be used to correct our dgps position
float64 lat
float64 lon
---
bool success