/**
 * @file teleop_drive_joy.hpp
 * @brief Header file for the TeleopDriveJoy class, which handles joystick input for teleoperation.
 * @author Dylan Gonzalez
 * Last Edited by Kabi
 */

#ifndef TELEOP_NOVA_JOY_TELEOP_NOVA_JOY_H
#define TELEOP_NOVA_JOY_TELEOP_NOVA_JOY_H

#include <rclcpp/rclcpp.hpp>
#include <sensor_msgs/msg/joy.hpp>
#include <geometry_msgs/msg/twist_stamped.hpp>
#include <drive_interfaces/msg/drive_input_stamped.hpp>
#include <drive_interfaces/msg/drive_info.hpp>
#include <controller_manager_msgs/srv/switch_controller.hpp>

// This Header is automatically generated by generate_parameter_library() while Building
// Edit teleop.config.yaml for modifying parameter schema
// For Intellisense to work, build the project using CMake once
#include "teleop_drive_joy_parameters.hpp"

namespace teleop_drive_joy
{

  /**
   * @enum ControlMode
   * @brief Enum class for different control modes.
   */
  enum class ControlMode
  {
    PIVOT_DRIVE,  // Pivot Drive Controller
    STRAFE_DRIVE, // Strafe Controller
    DIFF_DRIVE    // Nova Diff Drive Controller
  };

  inline std::string prettyPrintMode(ControlMode mode)
  {
    switch (mode)
    {
    case ControlMode::PIVOT_DRIVE:
      return "Pivot Mode";
    case ControlMode::STRAFE_DRIVE:
      return "Strafe Mode";
    case ControlMode::DIFF_DRIVE:
      return "Tank Mode";
    }
  }

  inline std::string modeToController(ControlMode mode)
  {
    switch (mode)
    {
    case ControlMode::PIVOT_DRIVE:
      return "pivot_drive_controller";
    case ControlMode::STRAFE_DRIVE:
      return "strafe_controller";
    case ControlMode::DIFF_DRIVE:
      return "nova_diff_drive_controller";
    }
  }

  /**
   * @class TeleopDriveJoy
   * @brief Class for handling joystick input and publishing drive commands.
   */
  class TeleopDriveJoy
  {
  public:
    /**
     * @brief Constructor for TeleopDriveJoy.
     * @param options Node options for the ROS2 node.
     */
    explicit TeleopDriveJoy(const rclcpp::NodeOptions &options);

    /**
     * @brief Callback function for joystick messages.
     * @param joy_msg Shared pointer to the joystick message.
     */
    void joyCallback(const sensor_msgs::msg::Joy::SharedPtr joy_msg);

    /**
     * @brief Handler for Button Presses.
     * @param joy_msg Shared pointer to the joystick message.
     */
    void handleButtonCallbacks(const sensor_msgs::msg::Joy::SharedPtr joy_msg);

    /**
     * @brief Sends a Drive Commmand on /drive_input or /cmd_vel based on joy.
     * @param joy_msg Shared pointer to the joystick message.
     * @param which_map Specifies which map to use for the command.
     */
    void sendDriveCommand(const sensor_msgs::msg::Joy::SharedPtr joy_msg);

    /**
     * @brief Switches the controller by calling controller_manager/switch_controller service
     *
     * @param control_mode The desired control mode to switch to.
     */
    void switchController(const ControlMode requested_control_mode);

    /**
     * @brief Gets a value from the joystick message based on the provided maps.
     * @param joy_msg Shared pointer to the joystick message.
     * @param axis_map Map of axis names to their indices.
     * @param scale_map Map of axis names to their scaling factors.
     * @param fieldname Name of the field to retrieve the value for.
     * @return The value from the joystick message.
     */
    double getVal(const sensor_msgs::msg::Joy::SharedPtr joy_msg, const std::map<std::string, int64_t> &axis_map,
                  const std::map<std::string, double> &scale_map, const std::string &fieldname);

    rclcpp::node_interfaces::NodeBaseInterface::SharedPtr get_node_base_interface(); // NOLINT

  private:
    const rclcpp::Node::SharedPtr node_;
    std::shared_ptr<teleop_drive_joy::ParamListener> param_listener_;
    teleop_drive_joy::Params params_;

    // ROS2 Pubs and Subs
    rclcpp::Publisher<geometry_msgs::msg::TwistStamped>::SharedPtr cmd_vel_pub;
    rclcpp::Publisher<drive_interfaces::msg::DriveInputStamped>::SharedPtr drive_input_pub;
    rclcpp::Publisher<drive_interfaces::msg::DriveInfo>::SharedPtr drive_info_pub;
    rclcpp::Client<controller_manager_msgs::srv::SwitchController>::SharedPtr switch_controller_client;
    rclcpp::Subscription<sensor_msgs::msg::Joy>::SharedPtr joy_sub;
    rclcpp::Client<rcl_interfaces::srv::SetParameters>::SharedPtr parameters_client;

    bool sent_lock_msg;
    bool speed_change_button_pressed;
    ControlMode control_mode = ControlMode::PIVOT_DRIVE;
    drive_interfaces::msg::DriveInfo current_state;
    drive_interfaces::msg::DriveInfo previous_state;

    std::map<std::string, int64_t> axis_linear_map;                        ///< Map of linear axis names to their indices.
    std::map<std::string, std::map<std::string, double>> scale_linear_map; ///< Map of linear axis names to their scaling factors.

    std::map<std::string, int64_t> axis_angular_map;                        ///< Map of angular axis names to their indices.
    std::map<std::string, std::map<std::string, double>> scale_angular_map; ///< Map of angular axis names to their scaling factors.
  };

} // namespace teleop_drive_joy

#endif // TELEOP_NOVA_JOY_TELEOP_NOVA_JOY_H
