/aruco_tracker:
  ros__parameters:
    aruco:
      adaptiveThreshConstant: 7.0
      adaptiveThreshWinSizeMax: 23
      adaptiveThreshWinSizeMin: 3
      adaptiveThreshWinSizeStep: 10
      cornerRefinementMaxIterations: 30
      cornerRefinementMethod: 2
      cornerRefinementMinAccuracy: 0.1
      cornerRefinementWinSize: 5
      errorCorrectionRate: 0.6
      markerBorderBits: 1
      maxErroneousBitsInBorderRate: 0.35
      maxMarkerPerimeterRate: 4.0
      minCornerDistanceRate: 0.05
      minDistanceToBorder: 3
      minMarkerDistanceRate: 0.05
      minMarkerPerimeterRate: 0.03
      minOtsuStdDev: 5.0
      perspectiveRemoveIgnoredMarginPerCell: 0.13
      perspectiveRemovePixelPerCell: 4
      polygonalApproxAccuracyRate: 0.03
    board_descriptions_path: ''
    cam_base_topic: /oak/rgb/image_rect
    image_is_rectified: true # Only true if subscribed to '/oak/rgb/image_rect' or rectified-image equivalent.
    image_sub_qos:
      depth: 1
      durability: 2
      reliability: 2
    marker_dict: 4X4_50
    marker_size: 0.1500 # marker_size refers to the sidelength of the marker (in m), which for URC 2024, will be 150 mm.
    output_frame: 'map' # Frame which AR marker position is published relative to.
    publish_tf: true
    qos_overrides:
      /tf:
        publisher:
          depth: 100
          durability: volatile
          history: keep_last
          reliability: reliable
    use_sim_time: false
