/oak:
  ros__parameters:
    camera:
      i_enable_imu: true
      i_enable_ir: true
      i_nn_type: spatial
      i_pipeline_type: RGBD
      i_restart_on_diagnostics_error: false
      i_tf_base_frame: oak
      i_tf_camera_name: oak
      i_tf_parent_frame: base_link #oak-d-base-frame
      i_usb_speed: SUPER_PLUS
    diagnostic_updater:
      period: 1.0
    imu:
      i_acc_cov: 0.0
      i_acc_freq: 400
      i_batch_report_threshold: 5
      i_enable_rotation: true
      i_get_base_device_timestamp: false
      i_gyro_cov: 0.0
      i_gyro_freq: 400
      i_max_batch_reports: 10
      i_message_type: IMU
      i_rot_cov: -1.0
      i_rotation_vector_type: GAME_ROTATION_VECTOR
      i_sync_method: LINEAR_INTERPOLATE_ACCEL
    left:
      i_height: 720
      i_max_q_size: 30
      i_publish_topic: false
      i_width: 1280
    nn:
      i_disable_resize: true
      i_num_inference_threads: 2
      i_num_pool_frames: 4
        #i_nn_config_path: src/ros/rover/core/resources/ARC_oakd_v8/ARC_oakd_v8.json
      i_nn_config_path: src/ros/rover/core/resources/yolov8_new/best.json
    rgb:
      i_enable_nn: false
      i_enable_preview: true
      i_fps: 5.0
      i_preview_height: 640 #300
      i_preview_size: 640
      i_preview_width: 640 #300
      i_publish_topic: false
      i_width: 1280
    right:
      i_enable_nn: false
      i_publish_topic: false
      i_reverse_stereo_socket_order: false
      i_height: 720
      i_width: 1280
    stereo:
      i_align_depth: true
      i_depth_filter_size: 5
      i_depth_preset: HIGH_ACCURACY
      i_disparity_width: DISPARITY_96
      i_enable_alpha_scaling: false
      i_enable_brightness_filter: false
      i_enable_companding: false
      i_enable_decimation_filter: true
      i_decimation_filter_decimation_mode: NON_ZERO_MEDIAN
      i_decimation_filter_decimation_factor: 2
      i_enable_disparity_shift: false
      i_enable_distortion_correction: false
      i_enable_lazy_publisher: true
      i_enable_spatial_filter: false
      i_enable_spatial_nn: true
      i_enable_speckle_filter: true
      i_enable_temporal_filter: false
      i_enable_threshold_filter: true
      i_extended_disp: false
      i_output_disparity: false
      i_publish_left_rect: false
      i_publish_right_rect: false
      i_publish_synced_rect_pair: false
      i_publish_topic: true
      i_rectify_edge_fill_color: 0
      i_width: 1280
    use_sim_time: false
/spatial_bb_node:
  ros__parameters:
    desqueeze: true
