/oak:
  ros__parameters:
    camera:
      i_nn_type: none
      i_enable_imu: true
      i_mx_id: 18443010315748F500 # Look for the O-Camera Sticker
      i_tf_parent_frame: camera_link
      i_tf_camera_model: OAK-D-LR
      i_publish_tf_from_calibration: true
    nn:
      i_disable_resize: true
      i_num_inference_threads: 2
      i_num_pool_frames: 4
      i_nn_config_path: auto_bringup/resources/YOLOv11/best.json
    imu:
      i_enable_rotation: true
      i_message_type:
        IMU
        #i_rotation_vector_type: ROTATION_VECTOR
    rgb:
      i_enable_nn: false
      i_enable_preview: false
      i_fps: 5.0
      i_preview_height: 640 #300
      i_preview_size: 640
      i_preview_width: 640 #300
      i_width: 1280
      i_isp_den: 3
      i_isp_num: 2
    left:
      i_set_isp_scale: true
      i_fps: 5.0
      #WLS filter
      #i_publish_topic: true
    right:
      i_fps: 5.0
    stereo:
      i_align_depth: true
      i_enable_speckle_filter: true
      i_enable_decimation_filter: true
      i_decimation_filter_decimation_factor: 2
      i_decimation_filter_decimation_mode: NON_ZERO_MEDIAN
      i_subpixel: false
      i_fps: 5.0
      i_enable_threshold_filter: true
      i_publish_right_rect: true
      #WLS filter
      #i_output_disparity: true
