controller_manager:
  ros__parameters:
    update_rate: 20 
    use_sim_time: false

    wheel_velocity_controller:
      type: velocity_controllers/JointGroupVelocityController

    pivot_position_controller:
      type: position_controllers/JointGroupPositionController

    pivot_joint_trajectory_controller:
      type: joint_trajectory_controller/JointTrajectoryController

    pivot_drive_controller:
      type: pivot_drive_controller/PivotDriveController

    strafe_controller:
      type: strafe_controller/StrafeController

    nova_diff_drive_controller:
      type: nova_diff_drive_controller/NovaDiffDriveController

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

wheel_velocity_controller:
  ros__parameters:
    joints:
      - flw
      - blw
      - brw
      - frw

pivot_position_controller:
  ros__parameters:
    joints:
      - flp
      - blp
      - brp
      - frp

joint_state_broadcaster:
  ros__parameters:
    interfaces:
       ["position",
      "velocity"]

    joints:
      ["blp",
      "brp",
      "flp",
      "frp",
      "blw",
      "brw",
      "flw",
      "frw"]

    use_local_topics: false
    
pivot_drive_controller:
  ros__parameters:
    enable_twist_cmd: true
    left_drive_names: ["flw", "blw"]
    right_drive_names: ["frw", "brw"]
    left_pivot_names: ["flp", "blp"]
    right_pivot_names: ["frp", "brp"]
    open_loop: false
    has_velocity_limits: true
    has_acceleration_limits: true
    max_velocity: 2.794144
    min_velocity: -2.794144 
    max_acceleration: 0.1
    min_acceleration: -0.1
    twist_covariance_diagonal: [0.1, 0.1, 0.1, 0.1, 0.1, 0.1]
    steering_track: 0.76
    wheel_base: 0.875
    wheel_radius: 0.15

strafe_controller:
  ros__parameters:
    enable_twist_cmd: true
    left_drive_names: ["flw", "blw"]
    right_drive_names: ["frw", "brw"]
    left_pivot_names: ["flp", "blp"]
    right_pivot_names: ["frp", "brp"]
    open_loop: true
    max_acceleration: 5.0
    wheel_radius: 0.16
    wheel_base: 0.875
    steering_track: 0.76

nova_diff_drive_controller:
  ros__parameters:
    enable_twist_cmd: true
    left_drive_names: ["flw", "blw"]
    right_drive_names: ["frw", "brw"]
    left_pivot_names: ["flp", "blp"]
    right_pivot_names: ["frp", "brp"]
    wheels_per_side: 2
    steering_track: 0.7
    wheel_base: 0.84
    wheel_radius: 0.1488
    linear:
      x:
        max_acceleration: 5.0
    twist_covariance_diagonal: [0.1, 0.1, 0.1, 0.1, 0.1, 0.1]

