/oak:
  ros__parameters:
    camera:
      i_nn_type: none
    rgb: 
      i_fps: 5.0
    left:
      i_fps: 5.0
    right:
      i_fps: 5.0
    stereo:
      # i_enable_distortion_correction: true
      # i_enable_spatial_filter: true
      i_enable_speckle_filter: true
      i_enable_threshold_filter: true
      i_align_depth: true
      i_board_socket_id: 2
      i_subpixel: true
      i_publish_right_rect: true
      i_enable_decimation_filter: true
      i_decimation_filter_decimation_factor: 2 
      i_decimation_filter_decimation_mode: NON_ZERO_MEDIAN
      i_subpixel: true
      i_fps: 5.0