# Params for RTABMap SLAM
rtabmap_slam:
  ros__parameters:
    qos: 1
    frame_id: base_link
    publish_tf: True
    subscribe_rgb: False
    subscribe_depth: False
    subscribe_rgbd: True
    rgbd_cameras: 2
    subscribe_odom_info: False
    approx_sync: True
    odom_frame_id: odom
    Rtabmap/DetectionRate: "3.5"
    # Grid Parameters are responsible for the Occupancy Grid Generated
    # Crucial for Costmap Generation
    Grid/MaxGroundAngle: "10"
    Grid/RangeMax: "5.0"
    Grid/RangeMin: "1.0"
    Grid/3D: "false" # Only Needed for 3D Planning
    Grid/MaxObstacleHeight: "1.0"
    Grid/NoiseFilteringRadius: "0.25"
    Grid/NoiseFilteringMinNeighbors: "5"
    Grid/CellSize: "0.1"
    GridGlobal/MinSize: "100.0"
    Grid/RayTracing: "true"
# Params for RGBD Odom (VO)
rtabmap_odom:
  ros__parameters:
    qos: 1
    publish_tf: False
    publish_null_when_lost: False
    subscribe_rgbd: True
    rgbd_cameras: 2

oak_rgbd_sync:
  ros__parameters:
    qos: 1

bootie_rgbd_sync:
  ros__parameters:
    qos: 1
