/**
 * Carousel GUI component
 * Author: Bailey Chessum
 * Date Created: 12/5/2024
 */
import React from "react";
import {
  Autocomplete,
  AutocompleteItem,
  Button,
  Card,
  CardBody,
  CardHeader,
  Select,
  SelectItem
} from "@nextui-org/react";

/**
 * Props for CarouselWidget
 */
export interface CarouselWidgetProps {
  // What values should be sent to the ROS node as positions to go to?
  instruments?: Map<string, number>;
  // The number of cuvette ids.
  cuvetteCount?: number;
  // Manual override of the cuvette ids generated by cuvetteCount
  cuvettes?: number[];
  embedded?: boolean;
}

/**
 * Widget that holds controls for moving the carousel to different positions.
 * It assumes that cuvette names are in the form of some index starting from 0 to some N
 * @constructor
 */
const CarouselWidget: React.FC<CarouselWidgetProps> = (props) => {
  // What values should be sent to the ROS node as positions to go to?
  const instruments = props.instruments ?? new Map<string, number>([
    ["Pumps", 0],
    ["UV Vis Spec", 5],
    ["Camera", 10],
  ]);

  // Definitions for cuvette ids from props, using defaults if not specified
  const cuvetteCount = props.cuvettes?.length ?? props.cuvetteCount ?? 20;
  const cuvettes = props.cuvettes ?? Array.from({ length: cuvetteCount }, (_, i) => i);

  // Picker for the cuvette
  const cuvettePicker = (
    <Autocomplete placeholder="#" label="Cuvette ID" allowsCustomValue className="col-span-2">
      {cuvettes.map((cuvette) => (
        <AutocompleteItem key={cuvette} value={cuvette}>
          {cuvette.toString()}
        </AutocompleteItem>
      ))}
    </Autocomplete>
  );

  // Picker for where to move the selected cuvette to
  const instrumentPicker = (
    <Select label="Instrument" placeholder="Select an instrument" className="col-span-2">
      {Array.from(instruments.entries()).map(([instrument, id], index) => (
        <SelectItem key={`instrument-${index}`} endContent={
          <span className="text-foreground-500">({id.toFixed(0)})</span>
        }>
          {instrument}
        </SelectItem>
      ))}
    </Select>
  );

  // Layout the pickers horizontally with even spacing
  const pickerRow = (
    <div className="grid auto-cols-fr gap-3 grid-cols-5 content-around">
      {instrumentPicker}
      {cuvettePicker}
      <Button color="primary" className="h-full">Go</Button>
    </div>
  );

  // Construct the widget
  return (
    <Card>
      <CardHeader>
        Carousel
      </CardHeader>
      <CardBody>
        {pickerRow}
      </CardBody>
    </Card>
  )
}

export default CarouselWidget;


