/**
 * Carousel GUI component
 * Author: Bailey Chessum
 * Date Created: 12/5/2024
 */
import React, {Key, useCallback, useState} from "react";
import {
  Autocomplete,
  AutocompleteItem,
  Button,
  Card,
  CardBody,
  CardHeader, CardProps, Dropdown, DropdownItem, DropdownMenu, DropdownTrigger,
  Select,
  SelectItem
} from "@nextui-org/react";
import {MoreHorizontal} from "react-feather";
import { useRosAction } from "../../hooks/ros/useRosAction";
import { RosAction } from "../../ros/actions/RosAction";
import { IRosNovaInterfacesStepperActionGoal, IRosNovaInterfacesStepperActionGoalConst } from "../../ros/rosTypes";

/**
 * Props for CarouselWidget
 */
export interface CarouselWidgetProps extends CardProps {
  // What values should be sent to the ROS node as positions to go to?
  instruments?: Map<string, number>;
  // The number of cuvette ids.
  cuvetteCount?: number;
  // Manual override of the cuvette ids generated by cuvetteCount
  cuvettes?: number[];
  embedded?: boolean;
}

/**
 * Widget that holds controls for moving the carousel to different positions.
 * It assumes that cuvette names are in the form of some index starting from 0 to some N
 * @constructor
 */
const CarouselWidget: React.FC<CarouselWidgetProps> = (props) => {
  const [ selectedCuvette, setSelectedCuvette ] = useState<Key>(0);

  // What values should be sent to the ROS node as positions to go to?
  const instruments = props.instruments ?? new Map<string, number>([
    ["UV Vis Spec", 16],
    ["Camera", 1],
  ]);

  // Definitions for cuvette ids from props, using defaults if not specified
  const cuvetteCount = props.cuvettes?.length ?? props.cuvetteCount ?? 20;
  const cuvettes = props.cuvettes ?? Array.from({ length: cuvetteCount }, (_, i) => i + 1);

  const { sendGoal, cancelGoal } = useRosAction(RosAction.CAROUSEL_ACTION);

  const cancel = useCallback(() => {
    cancelGoal();
  }, [cancelGoal]);

  const goToCarousel = useCallback(() => {
    if (!selectedCuvette) {
      return;
    }

    const action: IRosNovaInterfacesStepperActionGoal = { 
      goal: selectedCuvette.toString(),
      action: IRosNovaInterfacesStepperActionGoalConst.GO_TO
    };

    console.log(action);

    sendGoal(action);
  }, [sendGoal, selectedCuvette]);

  // Function that sets the carousel position when called
  const setCarousel = useCallback(() => {
    if (!selectedCuvette) {
      return;
    }

    const action: IRosNovaInterfacesStepperActionGoal = { 
      goal: selectedCuvette.toString(),
      action: IRosNovaInterfacesStepperActionGoalConst.SET
    };

    sendGoal(action);
  }, [sendGoal, selectedCuvette]);

  // Picker for the cuvette
  const cuvettePicker = (
    <Autocomplete placeholder="#" label="Cuvette ID" allowsCustomValue className="col-span-2" selectedKey={selectedCuvette?.toString()} onSelectionChange={(value) => setSelectedCuvette(value ?? 0)} onInputChange={setSelectedCuvette}>
      {cuvettes.map((cuvette) => (
        <AutocompleteItem key={`${cuvette}`} value={cuvette}>
          {cuvette.toString()}
        </AutocompleteItem>
      ))}
    </Autocomplete>
  );

  // Picker for where to move the selected cuvette to
  const instrumentPicker = (
    <Select label="Instrument" placeholder="Select an instrument" className="col-span-2">
      {Array.from(instruments.entries()).map(([instrument, id], index) => (
        <SelectItem key={index} endContent={
          <span className="text-foreground-500">({id.toFixed(0)})</span>
        }>
          {instrument}
        </SelectItem>
      ))}
    </Select>
  );

  // Layout the pickers horizontally with even spacing
  const pickerRow = (
    <div className="grid auto-cols-fr gap-3 grid-cols-6 grid-rows-2 content-around">
      {instrumentPicker}
      {cuvettePicker}
      <Button color="primary" className="h-full" onPress={goToCarousel}>Go To</Button>
    </div>
  );

  // The triple dots at the top right corner of the widget
  const cardHeaderDropdown = (
    <Dropdown className="m-0">
      <DropdownTrigger>
        <Button
          variant={"light"}
          isIconOnly
          className="m-0"
        >
          <MoreHorizontal></MoreHorizontal>
        </Button>
      </DropdownTrigger>
      <DropdownMenu aria-label="Static Actions">
        <DropdownItem key="set" onPress={setCarousel}>
          Set Carousel Position
        </DropdownItem>
      </DropdownMenu>
    </Dropdown>
  );

  // Construct the widget
  return (
    <Card {...props}>
      <CardHeader className="pb-0 flex flex-row">
        <div className="flex-grow">Carousel</div>
        {cardHeaderDropdown}
      </CardHeader>
      <CardBody>
        {pickerRow}
        <div className="flex flex-row mt-3 gap-5 justify-center">
          <Button color="warning" onPress={() => setCarousel()}>Set Stepper</Button>
          <Button color="danger" onPress={() => cancel()}>Cancel Action</Button>
        </div>
      </CardBody>
    </Card>
  )
}

export default CarouselWidget;


