bt_navigator:
  ros__parameters:
    global_frame: map
    robot_base_frame: base_link
    odom_topic: /odometry/filtered
    bt_loop_duration: 20
    default_server_timeout: 60000
    wait_for_service_timeout: 1000
    action_service_result_timeout: 900.0
    goal_offset_radius: 1.0 # should be more than robot radius
    error_code_names:
      - compute_path_error_code
      - follow_path_error_code
    navigators: ["navigate_to_pose", "navigate_through_poses", "urc_through_poses"]
    
    navigate_to_pose:
      plugin: "nav2_bt_navigator::NavigateToPoseNavigator"
    default_nav_to_pose_bt_xml: /home/nova/nova/src/ros/rover/auto/nova_behavior_tree/behavior_tree/shared/nav_to_pose.xml
    
    navigate_through_poses:
      plugin: "nav2_bt_navigator::NavigateThroughPosesNavigator"
    default_nav_through_poses_bt_xml: /home/nova/nova/src/ros/rover/auto/nova_behavior_tree/behavior_tree/shared/nav_through_poses_remove_in_collision_goals.xml
    
    urc_through_poses:
      plugin: "nova_bt_navigators::URCThroughPoses"
    default_urc_through_poses_bt_xml: /home/nova/nova/src/ros/rover/auto/nova_behavior_tree/behavior_tree/urc/urc_through_poses_aruco.xml
    
    plugin_lib_names:
      - nova_blackboard_publisher_bt_node
      - nova_remove_in_collision_goals_action_bt_node
      - nova_remove_passed_goal_action_bt_node
      - nova_ar_tag_detected_condition_bt_node
      - nova_get_goal_action_bt_node
      - nova_pop_goal_action_bt_node
      - nova_set_detection_goal_action_bt_node
      - nova_place_search_goals_action_bt_node
      - nova_object_detected_condition_bt_node
      - nova_goals_empty_condition_bt_node
      - nova_force_running_decorator_bt_node

bt_navigator_navigate_through_poses_rclcpp_node:
  ros__parameters:
    use_sim_time: False

bt_navigator_navigate_to_pose_rclcpp_node:
  ros__parameters:
    use_sim_time: False
