# Controllers for the new arm
arm:
  controller_manager:
    ros__parameters:
      update_rate: 100
      use_sim_time: false

      nova_arm_velocity_controller:
        type: nova_arm_controller/NovaArmController

      nova_arm_position_controller:
        type: nova_arm_controller/NovaArmController
      
      nova_end_effector_velocity_controller:
        type: nova_arm_controller/NovaArmController

      nova_twistmapper:
        type: nova_twistmapper/NovaTwistmapper
      
      nova_twistmapper_velocity:
        type: nova_twistmapper/NovaTwistmapper

      nova_path_planner:
        type: nova_path_planner/NovaPathPlanner

      joint_state_broadcaster_arm:
        type: joint_state_broadcaster/JointStateBroadcaster
      
      joint_state_broadcaster_end_effector:
        type: joint_state_broadcaster/JointStateBroadcaster

      joint_state_broadcaster_arm_telemetry:
        type: joint_state_broadcaster/JointStateBroadcaster

  nova_arm_velocity_controller:
    ros__parameters:
      topic: "/arm/joint_velocity_command"
      joint_names:
        - j1
        - j2
        - j3
        - j4
        - j5
        - j6
      use_position_control: false
      use_collision_limits: false
      do_4bar: true
      j2_minus_j3:
        j2_idx: 1 # this is badly designed.
        j3_idx: 2
        max_position: 0.8487
        min_position: -1.0
      velocity_feedback: true
      position_feedback: true
      use_limits: true
      joint_limits:
        j1:
          has_position_limits: true
          max_position: 1.57
          min_position: -1.57
          has_velocity_limits: true
          max_velocity: 0.188   #< matches teleop.yaml
        j2:
          has_position_limits: true
          max_position: 2.35
          min_position: -1.6364
          has_velocity_limits: true
          max_velocity: 0.188   #< matches teleop.yaml
        j3:
          has_position_limits: true
          max_position: 2.9
          min_position: -0.6535
          has_velocity_limits: true
          max_velocity: 0.188   #< matches teleop.yaml
        j4:
          has_position_limits: true
          max_position: 3.14
          min_position: -3.14
          has_velocity_limits: true
          max_velocity: 0.4     #< matches teleop.yaml
        j5: # wrist pitch
          has_position_limits: true
          max_position: 0.2
          min_position: -3.2
          has_velocity_limits: true
          max_velocity: 0.7     #< matches teleop.yaml
        j6: # wrist roll
          has_position_limits: true
          max_position: 7.5
          min_position: -7.5
          has_velocity_limits: true
          max_velocity: 0.7     #< matches teleop.yaml

  nova_arm_position_controller:
    ros__parameters:
      topic: "/arm/joint_position_command"
      joint_names:
        - j1
        - j2
        - j3
        - j4
        - j5
        - j6
      use_position_control: true
      velocity_feedback: true
      position_feedback: true
      use_collision_limits: false
      do_4bar: true
      j2_minus_j3:
        j2_idx: 1 # this is badly designed.
        j3_idx: 2
        max_position: 0.8487
        min_position: -1.0
      use_limits: true
      joint_limits:
        j1:
          has_position_limits: true
          max_position: 1.57
          min_position: -1.57
          has_velocity_limits: true
          max_velocity: 0.2
        j2:
          has_position_limits: true
          max_position: 2.35
          min_position: -1.6364
          has_velocity_limits: true
          max_velocity: 0.2
        j3:
          has_position_limits: true
          max_position: 2.9
          min_position: -0.6535
          has_velocity_limits: true
          max_velocity: 0.2
        j4:
          has_position_limits: true
          max_position: 3.14
          min_position: -3.14
          has_velocity_limits: true
          max_velocity: 0.2
        j5: # wrist pitch
          has_position_limits: true
          max_position: 0.2
          min_position: -3.2
          has_velocity_limits: true
          max_velocity: 0.5
        j6: # wrist roll
          has_position_limits: true
          max_position: 7.5
          min_position: -7.5
          has_velocity_limits: true
          max_velocity: 0.5
    
  nova_end_effector_velocity_controller:
    ros__parameters:
      topic: "/arm/end_effector_joint_velocity_command"
      joint_names:
        - lead_left_
        - la_prismatic_
      use_position_control: false
      use_collision_limits: false
      use_limits: true
      velocity_feedback: false
      position_feedback: false
      joint_limits:
        lead_left_:
          has_velocity_limits: true
          max_velocity: 10000.0 # these are crazy numbers
        la_prismatic_:
          has_velocity_limits: true
          max_velocity: 100000.0

  nova_twistmapper:
    ros__parameters:
      chained_controller_name: "nova_arm_position_controller"
      twist_stamped_topic: "/arm/task_space_twist_command"
      joint_names:
        - j1
        - j2
        - j3
        - j4
        - j5
        - j6
      use_position_control: true
      cmd_timeout: 0.5
      velocity_ik_time_step: 0.01
      use_control_period_for_velocity_ik: false
      max_velocity_control_period: 0.1
      fallback_frame_id: "endeffector_kinematics"
      publish_debug_frames: false
      base_link_name: "arm_kinematics_origin"
      ee_link_name: "endeffector_kinematics"
      kinematics_output_target_frame: "arm_twistmapper_target"
      self_intersection_max_step_size: 0.05
      kinematics:
        forward_kinematics_plugin: "arm_kinematics/DefaultForwardKinematicsPlugin"
        inverse_kinematics_plugin: "arm_kinematics/BanksiaIKPlugin"
        collision_plugin: "arm_kinematics/FclCollisionPlugin"
        default_state_interface_values:
          - "chassis_to_left_leg/position=0.0"
          - "chassis_to_right_leg/position=0.0"
          - "blp/position=0.0"
          - "brp/position=0.0"
          - "flp/position=0.0"
          - "frp/position=0.0"
          - "blw/position=0.0"
          - "brw/position=0.0"
          - "flw/position=0.0"
          - "frw/position=0.0"

      collision:
        generate_from_default_pose: true
        ignored_links:
          - diffbar
          - left_leg
          - right_leg
          - back_left_pivot
          - front_left_pivot
          - back_right_pivot
          - front_right_pivot
          - back_left_wheel
          - front_left_wheel
          - back_right_wheel
          - front_right_wheel
          - bl_ankle
          - fl_ankle
          - br_ankle
          - fr_ankle
          - bl_wheel
          - fl_wheel
          - br_wheel
          - fr_wheel

  nova_twistmapper_velocity:
    ros__parameters:
      chained_controller_name: "nova_arm_velocity_controller"
      twist_stamped_topic: "/arm/task_space_twist_command"
      joint_names:
        - j1
        - j2
        - j3
        - j4
        - j5
        - j6
      use_position_control: false
      cmd_timeout: 0.5
      velocity_ik_time_step: 0.01
      use_control_period_for_velocity_ik: false
      max_velocity_control_period: 0.1
      fallback_frame_id: "endeffector_kinematics"
      publish_debug_frames: false
      base_link_name: "arm_kinematics_origin"
      ee_link_name: "endeffector_kinematics"
      kinematics_output_target_frame: "arm_twistmapper_target"
      self_intersection_max_step_size: 0.05
      kinematics:
        forward_kinematics_plugin: "arm_kinematics/DefaultForwardKinematicsPlugin"
        inverse_kinematics_plugin: "arm_kinematics/BanksiaIKPlugin"
        collision_plugin: "arm_kinematics/FclCollisionPlugin"
        default_state_interface_values:
          - "chassis_to_left_leg/position=0.0"
          - "chassis_to_right_leg/position=0.0"
          - "blp/position=0.0"
          - "brp/position=0.0"
          - "flp/position=0.0"
          - "frp/position=0.0"
          - "blw/position=0.0"
          - "brw/position=0.0"
          - "flw/position=0.0"
          - "frw/position=0.0"

      collision:
        generate_from_default_pose: true
        ignored_links:
          - diffbar
          - left_leg
          - right_leg
          - back_left_pivot
          - front_left_pivot
          - back_right_pivot
          - front_right_pivot
          - back_left_wheel
          - front_left_wheel
          - back_right_wheel
          - front_right_wheel
          - bl_ankle
          - fl_ankle
          - br_ankle
          - fr_ankle
          - bl_wheel
          - fl_wheel
          - br_wheel
          - fr_wheel

  nova_path_planner:
    ros__parameters:
  #    chained_controller_name: "nova_arm_position_controller"
      chained_controller_name: ""
      joint_names:
        - j1
        - j2
        - j3
        - j4
        - j5
        - j6
      action_name: "/arm/plan_path"
      base_link_name: "arm_kinematics_origin"
      ee_link_name: "endeffector_kinematics"
      kinematics_output_target_frame: "arm_path_planner_target"
      self_intersection_max_step_size: 0.05
      kinematics:
        forward_kinematics_plugin: "arm_kinematics/DefaultForwardKinematicsPlugin"
        inverse_kinematics_plugin: "arm_kinematics/BanksiaIKPlugin"
        collision_plugin: "arm_kinematics/FclCollisionPlugin"
      collision:
        generate_from_default_pose: true
        ignored_links:
          - diffbar
          - left_leg
          - right_leg
          - back_left_pivot
          - front_left_pivot
          - back_right_pivot
          - front_right_pivot
          - back_left_wheel
          - front_left_wheel
          - back_right_wheel
          - front_right_wheel
          - bl_ankle
          - fl_ankle
          - br_ankle
          - fr_ankle
          - bl_wheel
          - fl_wheel
          - br_wheel
          - fr_wheel

  joint_state_broadcaster_arm:
    ros__parameters:
      interfaces:
         ["position", "velocity"]

      joints: ["j1", "j2", "j3", "j4", "j5", "j6"]
      use_local_topics: false
  
  joint_state_broadcaster_end_effector:
    ros__parameters:
      interfaces:
         ["velocity"]

      joints: ["la_prismatic_", "lead_left_"]
      use_local_topics: false

  joint_state_broadcaster_arm_telemetry:
    ros__parameters:
      update_rate: 10
      joints: ["j1", "j2", "j3", "j4", "j5", "j6"]
      interfaces: ["velocity", "effort"]
      publish_dynamic_joint_states: false
      use_local_topics: false