# base_frame: old arm = arm_link, new arm = arm_kinematics_origin
# handled in launch file

typing_sequencer:
  ros__parameters:
    # key position initalisation params
    keyboard_frame: keyboard_frame
    # base_frame: arm_link
    ee_frame: endeffector_kinematics
    actuator_frame: actuator

    timeout: 2.0
    pollrate: 10.0

    # path planner movement
    speed: 0.05 # m/s
    debug_target: True

pokey:
  ros__parameters:
    controllers:
      controller:
        duration: 5.0
    hardware:
      end_effector:
        can_id: 0x0C1