name: nova-cli tests 🖥️

on:
  pull_request:
    paths:
      - 'src/other/nova_cli/**'
  push:
    branches:
      - main
      - master
    paths:
      - 'src/other/nova_cli/**'

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install dependencies
        working-directory: src/other/nova_cli
        run: |
          pip install -e ".[test]"

      - name: Run tests
        working-directory: src/other/nova_cli
        run: pytest -v
