name: reviewdog 🐶

on:
  pull_request:
    paths:
      - 'src/ros/nova-gui/nova-gui/**'  # Only run when files in the nova-gui folder change
  push:
    branches:
      - main

jobs:
  reviewdog:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: "20"
      - name: Install dependencies
        working-directory: src/ros/nova-gui/nova-gui
        run: yarn install
      - name: Yarn Lint
        working-directory: src/ros/nova-gui/nova-gui
        run: yarn lint
        continue-on-error: true

      - uses: reviewdog/action-setup@v1
        with:
          reviewdog_version: latest
      - name: reviewdog
        working-directory: src/ros/nova-gui/nova-gui
        run: yarn lint | reviewdog -f=eslint -diff="git diff FETCH_HEAD"

      - uses: reviewdog/action-eslint@v1
        with:
          reporter: github-check
          workdir: 'src/ros/nova-gui/nova-gui'
